
# ft_sensor_filter:

  rate: 1000.0
  topic_name:
    raw: "ft_sensor/raw"
    filtered: "ft_sensor/filtered"

  cutoff_freq: 200.0
  lpf_order: 2
  deadzone:
    force:
      lower: -0.2
      upper: 0.2
    torque:
      lower: -0.1
      upper: 0.1
