
# ft_sensor_filter:

  rate: 500.0
  topic_name:
    raw: "ft_sensor/raw"
    filtered: "ft_sensor/filtered"

  cutoff_freq: 50.0
  lpf_order: 2
  deadzone:
    force:
      lower: -0.3
      upper: 0.3
    torque:
      lower: -0.1
      upper: 0.1
