OpenHRC: ArmPerception Class Reference
ArmPerception Class Reference
Public Member Functions
ArmPerception ()
int run ()
ArmPerception ()
int run ()
Private Types
enum Body {
Shoulder , Elbow , Wrist , NUM ,
Shoulder , Elbow , Wrist , NUM
}
enum Body {
Shoulder , Elbow , Wrist , NUM ,
Shoulder , Elbow , Wrist , NUM
}
Private Member Functions
void cbBodyMarker (const visualization_msgs::MarkerArray::ConstPtr &msg)
void cbBodyMarker (const visualization_msgs::MarkerArray::ConstPtr &msg)
Private Attributes
ros::NodeHandle n
ros::Subscriber sub
ros::Publisher pubMarker
tf2_ros::TransformBroadcaster br
TransformUtility trans
ros::Publisher bodyStatePublisher
ohrc_msgs::BodyState bodyState
Affine3d T_xr_camera
Detailed Description
Definition at line 17 of file human_arm_perception.cpp.
Member Enumeration Documentation
Body [1/2]
enum ArmPerception::Body private
Enumerator
Shoulder
Elbow
Wrist
NUM
Shoulder
Elbow
Wrist
NUM
Definition at line 18 of file human_arm_perception.cpp.
Body [2/2]
enum ArmPerception::Body private
Enumerator
Shoulder
Elbow
Wrist
NUM
Shoulder
Elbow
Wrist
NUM
Definition at line 19 of file k4abt_body_state_publisher.cpp.
Constructor & Destructor Documentation
ArmPerception() [1/2]
ArmPerception::ArmPerception ()
Definition at line 35 of file human_arm_perception.cpp.
References cbBodyMarker().
ArmPerception() [2/2]
ArmPerception::ArmPerception ()
Member Function Documentation
cbBodyMarker() [1/2]
void ArmPerception::cbBodyMarker (const visualization_msgs::MarkerArray::ConstPtr & msg) private
Definition at line 42 of file human_arm_perception.cpp.
References tf2::fromMsg(), ArmMarker::ManipulabilityEllipsoid, ArmMarker::Skeleton, promp_trajectory_demo::T, tf2::toMsg(), promp_trajectory_publisher::x, promp_trajectory_publisher::y, and promp_trajectory_publisher::z.
Referenced by ArmPerception().
cbBodyMarker() [2/2]
void ArmPerception::cbBodyMarker (const visualization_msgs::MarkerArray::ConstPtr & msg) private
run() [1/2]
int ArmPerception::run ()
Definition at line 182 of file human_arm_perception.cpp.
Referenced by main().
run() [2/2]
int ArmPerception::run ()
Member Data Documentation
bodyState
ohrc_msgs::BodyState ArmPerception::bodyState private
Definition at line 25 of file k4abt_body_state_publisher.cpp.
bodyStatePublisher
ros::Publisher ArmPerception::bodyStatePublisher private
Definition at line 23 of file k4abt_body_state_publisher.cpp.
br
tf2_ros::TransformBroadcaster ArmPerception::br private
Definition at line 24 of file human_arm_perception.cpp.
n
ros::NodeHandle ArmPerception::n private
Definition at line 20 of file human_arm_perception.cpp.
pubMarker
ros::Publisher ArmPerception::pubMarker private
Definition at line 22 of file human_arm_perception.cpp.
sub
ros::Subscriber ArmPerception::sub private
Definition at line 21 of file human_arm_perception.cpp.
T_xr_camera
Affine3d ArmPerception::T_xr_camera private
Definition at line 33 of file k4abt_body_state_publisher.cpp.
trans
TransformUtility ArmPerception::trans private
Definition at line 28 of file human_arm_perception.cpp.
The documentation for this class was generated from the following files:
human_arm_perception.cpp
k4abt_body_state_publisher.cpp