OpenHRC: SwitchingInterface< T1, T2 > Class Template Reference
SwitchingInterface< T1, T2 > Class Template Reference
#include <switching_interface.hpp>
Public Member Functions
SwitchingInterface (const std::shared_ptr< CartController > controller)
void updateTargetPose (KDL::Frame &pose, KDL::Twist &twist) override
void initInterface () override
void resetInterface () override
Protected Member Functions
void switchInterface ()
bool srvSwitchInterface (std_srvs::Empty::Request &req, std_srvs::Empty::Response &res)
Private Attributes
ros::ServiceServer srv
int cur_interface = 0
Detailed Description
template<class T1, class T2>
class SwitchingInterface< T1, T2 >
Definition at line 8 of file switching_interface.hpp.
Constructor & Destructor Documentation
SwitchingInterface()
template<class T1 , class T2 > SwitchingInterface< T1, T2 >::SwitchingInterface (const std::shared_ptr< CartController > controller) inline
Definition at line 32 of file switching_interface.hpp.
References SwitchingInterface< T1, T2 >::srv, and SwitchingInterface< T1, T2 >::srvSwitchInterface().
Member Function Documentation
initInterface()
template<class T1 , class T2 > void SwitchingInterface< T1, T2 >::initInterface () inline override
Definition at line 46 of file switching_interface.hpp.
resetInterface()
template<class T1 , class T2 > void SwitchingInterface< T1, T2 >::resetInterface () inline override
Definition at line 51 of file switching_interface.hpp.
srvSwitchInterface()
template<class T1 , class T2 > bool SwitchingInterface< T1, T2 >::srvSwitchInterface (std_srvs::Empty::Request & req, std_srvs::Empty::Response & res) inline protected
Definition at line 24 of file switching_interface.hpp.
References SwitchingInterface< T1, T2 >::switchInterface().
Referenced by SwitchingInterface< T1, T2 >::SwitchingInterface().
switchInterface()
template<class T1 , class T2 > void SwitchingInterface< T1, T2 >::switchInterface () inline protected
Definition at line 14 of file switching_interface.hpp.
References SwitchingInterface< T1, T2 >::cur_interface.
Referenced by SwitchingInterface< T1, T2 >::srvSwitchInterface().
updateTargetPose()
template<class T1 , class T2 > void SwitchingInterface< T1, T2 >::updateTargetPose (KDL::Frame & pose, KDL::Twist & twist) inline override
Definition at line 36 of file switching_interface.hpp.
References SwitchingInterface< T1, T2 >::cur_interface.
Member Data Documentation
cur_interface
template<class T1 , class T2 > int SwitchingInterface< T1, T2 >::cur_interface = 0 private
Definition at line 11 of file switching_interface.hpp.
Referenced by SwitchingInterface< T1, T2 >::switchInterface(), and SwitchingInterface< T1, T2 >::updateTargetPose().
srv
template<class T1 , class T2 > ros::ServiceServer SwitchingInterface< T1, T2 >::srv private
Definition at line 10 of file switching_interface.hpp.
Referenced by SwitchingInterface< T1, T2 >::SwitchingInterface().
The documentation for this class was generated from the following file:
switching_interface.hpp