OpenHRC: FeedbackController Class Reference
FeedbackController Class Reference
#include <feedback_controller.hpp>
Public Member Functions
virtual void updateTargetPose (KDL::Frame &pose, KDL::Twist &twist) override
virtual void initInterface () override
Interface (const std::shared_ptr< CartController > controller)
Public Member Functions inherited from Interface
Interface (const std::shared_ptr< CartController > controller)
virtual void resetInterface ()
virtual void feedback (const KDL::Frame &targetPos, const KDL::Twist &targetTwist)
std::string getTargetName ()
double getTargetDistance ()
TaskState getTaskState ()
Private Member Functions
VectorXd PIControl (const KDL::Frame &frame, const KDL::Frame &pose, const KDL::Twist &twist)
VectorXd adaptivePIControl (const KDL::Frame &frame, const KDL::Frame &pose, const KDL::Twist &twist)
VectorXd forceFeedbackControl (const KDL::Frame &frame, const KDL::Frame &pose, const VectorXd f)
Private Attributes
VectorXd x
VectorXd xd
std::vector< double > t0_f
Additional Inherited Members
Public Attributes inherited from Interface
int targetIdx = -1
int nCompletedTask = 0
bool blocked = false
Protected Member Functions inherited from Interface
void reset ()
void getTopicAndFrameName (std::string DefaultStateTopicName, std::string DefaultStateFrameId)
Protected Attributes inherited from Interface
ros::NodeHandle n
const double dt
std::shared_ptr< CartController > controller
ros::TransportHints th = ros::TransportHints().tcpNoDelay(true)
TaskState taskState = TaskState::Initial
std::string targetName
double targetDistance = 0.0
std::string stateTopicName = "/state"
std::string stateFrameId = "world"
Detailed Description
Definition at line 6 of file feedback_controller.hpp.
Member Function Documentation
adaptivePIControl()
VectorXd FeedbackController::adaptivePIControl (const KDL::Frame & frame, const KDL::Frame & pose, const KDL::Twist & twist) private
Definition at line 59 of file feedback_controller.cpp.
References pseudoSigmoid(), and t0_f.
Referenced by updateTargetPose().
forceFeedbackControl()
VectorXd FeedbackController::forceFeedbackControl (const KDL::Frame & frame, const KDL::Frame & pose, const VectorXd f) private
Definition at line 94 of file feedback_controller.cpp.
Referenced by updateTargetPose().
initInterface()
void FeedbackController::initInterface () override virtual
Reimplemented from Interface.
Definition at line 3 of file feedback_controller.cpp.
References t0_f.
Interface()
Interface::Interface inline
Definition at line 36 of file interface.hpp.
PIControl()
VectorXd FeedbackController::PIControl (const KDL::Frame & frame, const KDL::Frame & pose, const KDL::Twist & twist) private
Definition at line 77 of file feedback_controller.cpp.
Referenced by updateTargetPose().
updateTargetPose()
void FeedbackController::updateTargetPose (KDL::Frame & pose, KDL::Twist & twist) override virtual
Reimplemented from Interface.
Definition at line 7 of file feedback_controller.cpp.
References adaptivePIControl(), Interface::controller, forceFeedbackControl(), PIControl(), and t0_f.
Member Data Documentation
t0_f
std::vector<double> FeedbackController::t0_f private
Definition at line 13 of file feedback_controller.hpp.
Referenced by adaptivePIControl(), initInterface(), and updateTargetPose().
x
VectorXd FeedbackController::x private
Definition at line 7 of file feedback_controller.hpp.
xd
VectorXd FeedbackController::xd private
Definition at line 7 of file feedback_controller.hpp.
The documentation for this class was generated from the following files:
feedback_controller.hpp
feedback_controller.cpp