OpenHRC: BodyStatePrediction Class Reference
BodyStatePrediction Class Reference
Public Member Functions
BodyStatePrediction ()
int run ()
Private Member Functions
void cbBodyState (const ohrc_msgs::BodyState::ConstPtr &msg)
void publishBodyStateMarker (const ohrc_msgs::BodyState &bodyState)
void predictBodyState (ohrc_msgs::BodyState &bodyState)
Private Attributes
ros::NodeHandle n
ros::Subscriber sub
ros::Publisher bodyStateMarkerPublisher
ohrc_msgs::BodyState _bodyState
std::mutex mtx
Detailed Description
Definition at line 6 of file body_state_prediction.cpp.
Constructor & Destructor Documentation
BodyStatePrediction()
BodyStatePrediction::BodyStatePrediction ()
Definition at line 24 of file body_state_prediction.cpp.
References bodyStateMarkerPublisher, cbBodyState(), n, and sub.
Member Function Documentation
cbBodyState()
void BodyStatePrediction::cbBodyState (const ohrc_msgs::BodyState::ConstPtr & msg) private
Definition at line 29 of file body_state_prediction.cpp.
References _bodyState, and mtx.
Referenced by BodyStatePrediction().
predictBodyState()
void BodyStatePrediction::predictBodyState (ohrc_msgs::BodyState & bodyState) private
Definition at line 67 of file body_state_prediction.cpp.
Referenced by run().
publishBodyStateMarker()
void BodyStatePrediction::publishBodyStateMarker (const ohrc_msgs::BodyState & bodyState) private
Definition at line 34 of file body_state_prediction.cpp.
References bodyStateMarkerPublisher.
Referenced by run().
run()
int BodyStatePrediction::run ()
Definition at line 71 of file body_state_prediction.cpp.
References _bodyState, mtx, predictBodyState(), and publishBodyStateMarker().
Referenced by main().
Member Data Documentation
_bodyState
ohrc_msgs::BodyState BodyStatePrediction::_bodyState private
Definition at line 11 of file body_state_prediction.cpp.
Referenced by cbBodyState(), and run().
bodyStateMarkerPublisher
ros::Publisher BodyStatePrediction::bodyStateMarkerPublisher private
Definition at line 9 of file body_state_prediction.cpp.
Referenced by BodyStatePrediction(), and publishBodyStateMarker().
mtx
std::mutex BodyStatePrediction::mtx private
Definition at line 13 of file body_state_prediction.cpp.
Referenced by cbBodyState(), and run().
n
ros::NodeHandle BodyStatePrediction::n private
Definition at line 7 of file body_state_prediction.cpp.
Referenced by BodyStatePrediction().
sub
ros::Subscriber BodyStatePrediction::sub private
Definition at line 8 of file body_state_prediction.cpp.
Referenced by BodyStatePrediction().
The documentation for this class was generated from the following file:
body_state_prediction.cpp