OpenHRC: math_utility::Integrator Class Reference
math_utility::Integrator Class Reference
#include <math_utility.h>
Public Types
enum class Method { Euler , RungeKutta }
Public Member Functions
Integrator (const Method method, std::function< Eigen::VectorXd(const double &t, const Eigen::VectorXd &, const std::unordered_map< std::string, Eigen::MatrixXd > &)> f, double dt)
Public Attributes
std::function< Eigen::VectorXd(const double &t, const Eigen::VectorXd &, const std::unordered_map< std::string, Eigen::MatrixXd > &)> integrate
Private Member Functions
Eigen::VectorXd EulerIntegrate (const double &t, const Eigen::VectorXd &x, const std::unordered_map< std::string, Eigen::MatrixXd > &u)
Eigen::VectorXd RungeKuttaIntegrate (const double &t, const Eigen::VectorXd &x, const std::unordered_map< std::string, Eigen::MatrixXd > &u)
Private Attributes
const double dt
std::function< Eigen::VectorXd(const double &t, const Eigen::VectorXd &, const std::unordered_map< std::string, Eigen::MatrixXd > &)> f
Detailed Description
Definition at line 126 of file math_utility.h.
Member Enumeration Documentation
Method
enum math_utility::Integrator::Method strong
Enumerator
Euler
RungeKutta
Definition at line 144 of file math_utility.h.
Constructor & Destructor Documentation
Integrator()
math_utility::Integrator::Integrator (const Method method, std::function< Eigen::VectorXd(const double &t, const Eigen::VectorXd &, const std::unordered_map< std::string, Eigen::MatrixXd > &)> f, double dt) inline
Definition at line 145 of file math_utility.h.
References Euler, EulerIntegrate(), integrate, RungeKutta, RungeKuttaIntegrate(), and promp_trajectory_publisher::x.
Member Function Documentation
EulerIntegrate()
Eigen::VectorXd math_utility::Integrator::EulerIntegrate (const double & t, const Eigen::VectorXd & x, const std::unordered_map< std::string, Eigen::MatrixXd > & u) inline private
Definition at line 127 of file math_utility.h.
References dt, f, and promp_trajectory_publisher::x.
Referenced by Integrator().
RungeKuttaIntegrate()
Eigen::VectorXd math_utility::Integrator::RungeKuttaIntegrate (const double & t, const Eigen::VectorXd & x, const std::unordered_map< std::string, Eigen::MatrixXd > & u) inline private
Definition at line 131 of file math_utility.h.
References dt, f, and promp_trajectory_publisher::x.
Referenced by Integrator().
Member Data Documentation
dt
const double math_utility::Integrator::dt private
Definition at line 140 of file math_utility.h.
Referenced by EulerIntegrate(), and RungeKuttaIntegrate().
f
std::function<Eigen::VectorXd(const double& t, const Eigen::VectorXd&, const std::unordered_map<std::string, Eigen::MatrixXd>&)> math_utility::Integrator::f private
Definition at line 141 of file math_utility.h.
Referenced by EulerIntegrate(), and RungeKuttaIntegrate().
integrate
std::function<Eigen::VectorXd(const double& t, const Eigen::VectorXd&, const std::unordered_map<std::string, Eigen::MatrixXd>&)> math_utility::Integrator::integrate
Definition at line 154 of file math_utility.h.
Referenced by Integrator().
The documentation for this class was generated from the following file:
math_utility.h