OpenHRC: MyIK::MyIK Class Reference
MyIK::MyIK Class Reference
#include <my_ik.hpp>
Public Member Functions
VectorXd getUpdatedJntLimit (const KDL::JntArray &q_cur, std::vector< double > &artificial_lower_limits, std::vector< double > &artificial_upper_limits, const double &dt)
VectorXd getUpdatedJntVelLimit (const KDL::JntArray &q_cur, std::vector< double > &lower_vel_limits, std::vector< double > &upper_vel_limits, const double &dt)
MyIK (const std::string &base_link, const std::string &tip_link, const std::string &URDF_param="/robot_description", double _eps=1e-5, Affine3d T_base_world=Affine3d::Identity(), SolveType _type=Pure)
MyIK (const KDL::Chain &_chain, const KDL::JntArray &_q_min, const KDL::JntArray &_q_max, double _eps=1e-5, Affine3d T_base_world=Affine3d::Identity(), SolveType _type=Pure)
MyIK (const std::vector< std::string > &base_link, const std::vector< std::string > &tip_link, const std::vector< Affine3d > &T_base_world, const std::vector< std::shared_ptr< MyIK >> &myik_ptr, double _eps=1e-5, SolveType _type=Pure)
int CartToJnt (const KDL::JntArray &q_init, const KDL::Frame &p_in, KDL::JntArray &q_out, const double &dt=1.0e5)
int CartToJnt (const std::vector< KDL::JntArray > &q_init, const std::vector< KDL::Frame > &p_in, std::vector< KDL::JntArray > &q_out, const double &dt)
int CartToJntVel (const KDL::JntArray &q_cur, const KDL::Frame &des_eff_pose, const KDL::Twist &des_eff_vel, KDL::JntArray &dq_des, const double &dt=1.0e-5)
int CartToJntVel_pinv (const KDL::JntArray &q_cur, const KDL::Frame &des_eff_pose, const KDL::Twist &des_eff_vel, KDL::JntArray &dq_des, const double &dt)
int CartToJntVel_qp (const KDL::JntArray &q_cur, const KDL::Frame &des_eff_pose, const KDL::Twist &des_eff_vel, KDL::JntArray &dq_des, const double &dt)
int CartToJntVel_qp (const KDL::JntArray &q_cur, const KDL::Twist &des_eff_vel, const VectorXd &e, KDL::JntArray &dq_des, const double &dt)
int CartToJntVel_qp (const std::vector< KDL::JntArray > &q_cur, const std::vector< KDL::Frame > &des_eff_pose, const std::vector< KDL::Twist > &des_eff_vel, std::vector< KDL::JntArray > &dq_des, const double &dt)
int CartToJntVel_qp_manipOpt (const KDL::JntArray &q_cur, const KDL::Frame &des_eff_pose, const KDL::Twist &des_eff_vel, KDL::JntArray &dq_des, const double &dt, const MatrixXd &userManipU)
void updateVelP (const KDL::JntArray &q_cur, const KDL::Frame &des_eff_pose, KDL::Twist &des_eff_vel, const VectorXd &e)
VectorXd getRandomJnt (const double &dt)
VectorXd getRandomJntVel (const double &dt)
void resetRobotWeight ()
void setRobotWeight (int robotIndex, double rate)
void setqRest (const std::vector< KDL::JntArray > &q_rest)
int JntToCart (const KDL::JntArray &q_in, KDL::Frame &p_out)
int JntToCart (const KDL::JntArray &q_in, std::vector< KDL::Frame > &p_out)
int JntToCart (const KDL::JntArray &q_in, const KDL::JntArray &dq_in, KDL::Frame &p_out, KDL::Twist &v_out)
int JntToJac (const KDL::JntArray &q_in, KDL::Jacobian &jac)
int JntToJac (const KDL::JntArray &q_in, KDL::Jacobian &jac, int segmentNR)
int JntToJac (const KDL::JntArray &q_in, MatrixXd &J)
Affine3d getT_base_world ()
int JntVelToCartVel (const KDL::JntArray &q_in, const KDL::JntArray &dq_in, KDL::Twist &v_out)
visualization_msgs::Marker getManipulabilityMarker (const KDL::JntArray q_cur)
bool getKDLChain (KDL::Chain &chain_)
unsigned int getNJnt ()
unsigned int getNSeg ()
void setNameJnt (std::vector< std::string > name)
void setIdxSegJnt (std::vector< int > idx)
std::vector< int > getIdxSegJnt ()
void enablePoseFeedback ()
void disablePoseFeedback ()
bool getPoseFeedbackDisabled ()
bool getInitialized ()
Public Attributes
std::vector< std::shared_ptr< MyIK > > myIKs
int nState = 0
std::vector< int > iJnt
const int nRobot
Private Member Functions
void initializeSingleRobot (const KDL::Chain &chain)
int addSelfCollisionAvoidance (const KDL::JntArray &q_cur, std::vector< double > &lower_vel_limits_, std::vector< double > &upper_vel_limits_, std::vector< MatrixXd > &A_ca)
int addCollisionAvoidance (const std::vector< Affine3d > &Ts, const std::vector< MatrixXd > &Js_, std::vector< double > &lower_vel_limits_, std::vector< double > &upper_vel_limits_, std::vector< MatrixXd > &A_ca)
int addCollisionAvoidance (const std::vector< KDL::JntArray > &q_cur, std::vector< double > &lower_vel_limits_, std::vector< double > &upper_vel_limits_, std::vector< MatrixXd > &A_ca)
int calcCollisionAvoidance (int c0, int c1, const std::vector< std::vector< Vector3d >> &p_all, const std::vector< std::vector< KDL::Jacobian >> &J_all, double ds, double di, double eta, std::vector< double > &lower_vel_limits_, std::vector< double > &upper_vel_limits_, std::vector< MatrixXd > &A_ca)
bool getClosestPointLineSegments (const Vector3d &a0, const Vector3d &a1, const Vector3d &b0, const Vector3d &b1, double &as, double &bs)
double getDistance (const Vector3d &a0, const Vector3d &a1, const Vector3d &b0, const Vector3d &b1, const double &as, const double &bs)
Vector3d getVec (const Vector3d &a0, const Vector3d &a1, const Vector3d &b0, const Vector3d &b1, const double &as, const double &bs)
Private Attributes
bool initialized
bool enableSelfCollisionAvoidance = false
KDL::Chain chain
KDL::JntArray lb
KDL::JntArray ub
KDL::JntArray vb
double eps
SolveType solvetype
std::vector< BasicJointType > types
std::mutex mtx_
std::vector< KDL::JntArray > solutions
std::vector< std::pair< double, uint > > errors
KDL::Twist bounds
std::vector< double > best_x
int progress
bool aborted
unsigned int nJnt
unsigned int nSeg
std::unique_ptr< KDL::ChainJntToJacSolver > jacsolver
std::unique_ptr< KDL::ChainFkSolverPos_recursive > fksolver
std::unique_ptr< KDL::ChainFkSolverVel_recursive > fkVelSolver
Affine3d T_base_world
std::vector< std::string > nameJnt
std::vector< int > idxSegJnt
bool poseFeedbackDisabled = false
std::vector< std::vector< long long > > combsRobot
std::vector< std::vector< long long > > combosLink
bool enableCollisionAvoidance = true
std::vector< double > w_h
std::vector< double > init_w_h
std::vector< KDL::JntArray > q_rest
int nAddObj = 2
Eigen::Matrix< double, Eigen::Dynamic, 1 > primalVariable
Detailed Description
Definition at line 28 of file my_ik.hpp.
Constructor & Destructor Documentation
MyIK() [1/3]
MyIK::MyIK::MyIK (const std::string & base_link, const std::string & tip_link, const std::string & URDF_param = "/robot_description", double _eps = 1e-5, Affine3d T_base_world = Affine3d::Identity(), SolveType _type = Pure)
Definition at line 5 of file my_ik.cpp.
References model_utility::getBounds(), model_utility::getKDLChain(), and model_utility::getURDFModel().
MyIK() [2/3]
MyIK::MyIK::MyIK (const KDL::Chain & _chain, const KDL::JntArray & _q_min, const KDL::JntArray & _q_max, double _eps = 1e-5, Affine3d T_base_world = Affine3d::Identity(), SolveType _type = Pure)
Definition at line 27 of file my_ik.cpp.
MyIK() [3/3]
MyIK::MyIK::MyIK (const std::vector< std::string > & base_link, const std::vector< std::string > & tip_link, const std::vector< Affine3d > & T_base_world, const std::vector< std::shared_ptr< MyIK >> & myik_ptr, double _eps = 1e-5, SolveType _type = Pure)
Definition at line 32 of file my_ik.cpp.
References std_utility::comb().
Member Function Documentation
addCollisionAvoidance() [1/2]
int MyIK::MyIK::addCollisionAvoidance (const std::vector< Affine3d > & Ts, const std::vector< MatrixXd > & Js_, std::vector< double > & lower_vel_limits_, std::vector< double > & upper_vel_limits_, std::vector< MatrixXd > & A_ca) private
Definition at line 867 of file my_ik.cpp.
References std_utility::comb().
addCollisionAvoidance() [2/2]
int MyIK::MyIK::addCollisionAvoidance (const std::vector< KDL::JntArray > & q_cur, std::vector< double > & lower_vel_limits_, std::vector< double > & upper_vel_limits_, std::vector< MatrixXd > & A_ca) private
Definition at line 946 of file my_ik.cpp.
References std_utility::comb().
addSelfCollisionAvoidance()
int MyIK::MyIK::addSelfCollisionAvoidance (const KDL::JntArray & q_cur, std::vector< double > & lower_vel_limits_, std::vector< double > & upper_vel_limits_, std::vector< MatrixXd > & A_ca) private
Definition at line 808 of file my_ik.cpp.
References count.
calcCollisionAvoidance()
int MyIK::MyIK::calcCollisionAvoidance (int c0, int c1, const std::vector< std::vector< Vector3d >> & p_all, const std::vector< std::vector< KDL::Jacobian >> & J_all, double ds, double di, double eta, std::vector< double > & lower_vel_limits_, std::vector< double > & upper_vel_limits_, std::vector< MatrixXd > & A_ca) private
Definition at line 895 of file my_ik.cpp.
CartToJnt() [1/2]
int MyIK::MyIK::CartToJnt (const KDL::JntArray & q_init, const KDL::Frame & p_in, KDL::JntArray & q_out, const double & dt = 1.0e5)
Definition at line 196 of file my_ik.cpp.
References std_utility::makeVector().
CartToJnt() [2/2]
int MyIK::MyIK::CartToJnt (const std::vector< KDL::JntArray > & q_init, const std::vector< KDL::Frame > & p_in, std::vector< KDL::JntArray > & q_out, const double & dt)
Definition at line 203 of file my_ik.cpp.
References MyIK::getCartError(), and promp_trajectory_demo::T.
CartToJntVel()
int MyIK::MyIK::CartToJntVel (const KDL::JntArray & q_cur, const KDL::Frame & des_eff_pose, const KDL::Twist & des_eff_vel, KDL::JntArray & dq_des, const double & dt = 1.0e-5)
Definition at line 304 of file my_ik.cpp.
CartToJntVel_pinv()
int MyIK::MyIK::CartToJntVel_pinv (const KDL::JntArray & q_cur, const KDL::Frame & des_eff_pose, const KDL::Twist & des_eff_vel, KDL::JntArray & dq_des, const double & dt)
Definition at line 315 of file my_ik.cpp.
References MyIK::getCartError(), and promp_trajectory_demo::T.
CartToJntVel_qp() [1/3]
int MyIK::MyIK::CartToJntVel_qp (const KDL::JntArray & q_cur, const KDL::Frame & des_eff_pose, const KDL::Twist & des_eff_vel, KDL::JntArray & dq_des, const double & dt)
Definition at line 486 of file my_ik.cpp.
References std_utility::makeVector().
CartToJntVel_qp() [2/3]
int MyIK::MyIK::CartToJntVel_qp (const KDL::JntArray & q_cur, const KDL::Twist & des_eff_vel, const VectorXd & e, KDL::JntArray & dq_des, const double & dt)
CartToJntVel_qp() [3/3]
int MyIK::MyIK::CartToJntVel_qp (const std::vector< KDL::JntArray > & q_cur, const std::vector< KDL::Frame > & des_eff_pose, const std::vector< KDL::Twist > & des_eff_vel, std::vector< KDL::JntArray > & dq_des, const double & dt)
Definition at line 493 of file my_ik.cpp.
References std_utility::concatenateVectors(), MyIK::getCartError(), and std_utility::weightedSum().
CartToJntVel_qp_manipOpt()
int MyIK::MyIK::CartToJntVel_qp_manipOpt (const KDL::JntArray & q_cur, const KDL::Frame & des_eff_pose, const KDL::Twist & des_eff_vel, KDL::JntArray & dq_des, const double & dt, const MatrixXd & userManipU)
Definition at line 649 of file my_ik.cpp.
References MyIK::getCartError(), rotation_util::getRotationMatrixError(), promp_trajectory_demo::T, and std_utility::weightedSum().
disablePoseFeedback()
void MyIK::MyIK::disablePoseFeedback () inline
Definition at line 226 of file my_ik.hpp.
enablePoseFeedback()
void MyIK::MyIK::enablePoseFeedback () inline
Definition at line 223 of file my_ik.hpp.
getClosestPointLineSegments()
bool MyIK::MyIK::getClosestPointLineSegments (const Vector3d & a0, const Vector3d & a1, const Vector3d & b0, const Vector3d & b1, double & as, double & bs) private
Definition at line 1001 of file my_ik.cpp.
getDistance()
double MyIK::MyIK::getDistance (const Vector3d & a0, const Vector3d & a1, const Vector3d & b0, const Vector3d & b1, const double & as, const double & bs) private
Definition at line 1088 of file my_ik.cpp.
getIdxSegJnt()
std::vector<int> MyIK::MyIK::getIdxSegJnt () inline
Definition at line 219 of file my_ik.hpp.
getInitialized()
bool MyIK::MyIK::getInitialized () inline
Definition at line 233 of file my_ik.hpp.
getKDLChain()
bool MyIK::MyIK::getKDLChain (KDL::Chain & chain_) inline
Definition at line 198 of file my_ik.hpp.
getManipulabilityMarker()
visualization_msgs::Marker MyIK::MyIK::getManipulabilityMarker (const KDL::JntArray q_cur)
Definition at line 771 of file my_ik.cpp.
References promp_trajectory_demo::T, and tf2::toMsg().
getNJnt()
unsigned int MyIK::MyIK::getNJnt () inline
Definition at line 203 of file my_ik.hpp.
getNSeg()
unsigned int MyIK::MyIK::getNSeg () inline
Definition at line 207 of file my_ik.hpp.
getPoseFeedbackDisabled()
bool MyIK::MyIK::getPoseFeedbackDisabled () inline
Definition at line 229 of file my_ik.hpp.
getRandomJnt()
VectorXd MyIK::MyIK::getRandomJnt (const double & dt)
Definition at line 163 of file my_ik.cpp.
References geometry_msgs_utility::dist().
getRandomJntVel()
VectorXd MyIK::MyIK::getRandomJntVel (const double & dt)
Definition at line 179 of file my_ik.cpp.
References geometry_msgs_utility::dist().
getT_base_world()
Affine3d MyIK::MyIK::getT_base_world () inline
Definition at line 181 of file my_ik.hpp.
getUpdatedJntLimit()
VectorXd MyIK::MyIK::getUpdatedJntLimit (const KDL::JntArray & q_cur, std::vector< double > & artificial_lower_limits, std::vector< double > & artificial_upper_limits, const double & dt)
Definition at line 100 of file my_ik.cpp.
References MyIK::Continuous, MyIK::TransJoint, and promp_trajectory_publisher::x.
getUpdatedJntVelLimit()
VectorXd MyIK::MyIK::getUpdatedJntVelLimit (const KDL::JntArray & q_cur, std::vector< double > & lower_vel_limits, std::vector< double > & upper_vel_limits, const double & dt)
Definition at line 147 of file my_ik.cpp.
References promp_trajectory_publisher::x.
getVec()
Vector3d MyIK::MyIK::getVec (const Vector3d & a0, const Vector3d & a1, const Vector3d & b0, const Vector3d & b1, const double & as, const double & bs) private
Definition at line 1092 of file my_ik.cpp.
initializeSingleRobot()
void MyIK::MyIK::initializeSingleRobot (const KDL::Chain & chain) private
Definition at line 59 of file my_ik.cpp.
References MyIK::Continuous, MyIK::RotJoint, and MyIK::TransJoint.
JntToCart() [1/3]
int MyIK::MyIK::JntToCart (const KDL::JntArray & q_in, const KDL::JntArray & dq_in, KDL::Frame & p_out, KDL::Twist & v_out) inline
Definition at line 148 of file my_ik.hpp.
JntToCart() [2/3]
int MyIK::MyIK::JntToCart (const KDL::JntArray & q_in, KDL::Frame & p_out) inline
Definition at line 140 of file my_ik.hpp.
JntToCart() [3/3]
int MyIK::MyIK::JntToCart (const KDL::JntArray & q_in, std::vector< KDL::Frame > & p_out) inline
Definition at line 144 of file my_ik.hpp.
JntToJac() [1/3]
int MyIK::MyIK::JntToJac (const KDL::JntArray & q_in, KDL::Jacobian & jac) inline
Definition at line 157 of file my_ik.hpp.
JntToJac() [2/3]
int MyIK::MyIK::JntToJac (const KDL::JntArray & q_in, KDL::Jacobian & jac, int segmentNR) inline
Definition at line 164 of file my_ik.hpp.
JntToJac() [3/3]
int MyIK::MyIK::JntToJac (const KDL::JntArray & q_in, MatrixXd & J) inline
Definition at line 171 of file my_ik.hpp.
JntVelToCartVel()
int MyIK::MyIK::JntVelToCartVel (const KDL::JntArray & q_in, const KDL::JntArray & dq_in, KDL::Twist & v_out) inline
Definition at line 185 of file my_ik.hpp.
resetRobotWeight()
void MyIK::MyIK::resetRobotWeight ()
Definition at line 1098 of file my_ik.cpp.
setIdxSegJnt()
void MyIK::MyIK::setIdxSegJnt (std::vector< int > idx) inline
Definition at line 215 of file my_ik.hpp.
setNameJnt()
void MyIK::MyIK::setNameJnt (std::vector< std::string > name) inline
Definition at line 211 of file my_ik.hpp.
setqRest()
void MyIK::MyIK::setqRest (const std::vector< KDL::JntArray > & q_rest)
Definition at line 863 of file my_ik.cpp.
setRobotWeight()
void MyIK::MyIK::setRobotWeight (int robotIndex, double rate)
Definition at line 1101 of file my_ik.cpp.
References promp_trajectory_publisher::rate.
updateVelP()
void MyIK::MyIK::updateVelP (const KDL::JntArray & q_cur, const KDL::Frame & des_eff_pose, KDL::Twist & des_eff_vel, const VectorXd & e)
Definition at line 290 of file my_ik.cpp.
Member Data Documentation
aborted
bool MyIK::MyIK::aborted private
Definition at line 49 of file my_ik.hpp.
best_x
std::vector<double> MyIK::MyIK::best_x private
Definition at line 47 of file my_ik.hpp.
bounds
KDL::Twist MyIK::MyIK::bounds private
Definition at line 45 of file my_ik.hpp.
chain
KDL::Chain MyIK::MyIK::chain private
Definition at line 31 of file my_ik.hpp.
combosLink
std::vector<std::vector<long long> > MyIK::MyIK::combosLink private
Definition at line 69 of file my_ik.hpp.
combsRobot
std::vector<std::vector<long long> > MyIK::MyIK::combsRobot private
Definition at line 69 of file my_ik.hpp.
enableCollisionAvoidance
bool MyIK::MyIK::enableCollisionAvoidance = true private
Definition at line 82 of file my_ik.hpp.
enableSelfCollisionAvoidance
bool MyIK::MyIK::enableSelfCollisionAvoidance = false private
Definition at line 29 of file my_ik.hpp.
eps
double MyIK::MyIK::eps private
Definition at line 34 of file my_ik.hpp.
errors
std::vector<std::pair<double, uint> > MyIK::MyIK::errors private
Definition at line 42 of file my_ik.hpp.
fksolver
std::unique_ptr<KDL::ChainFkSolverPos_recursive> MyIK::MyIK::fksolver private
Definition at line 54 of file my_ik.hpp.
fkVelSolver
std::unique_ptr<KDL::ChainFkSolverVel_recursive> MyIK::MyIK::fkVelSolver private
Definition at line 55 of file my_ik.hpp.
idxSegJnt
std::vector<int> MyIK::MyIK::idxSegJnt private
Definition at line 60 of file my_ik.hpp.
iJnt
std::vector<int> MyIK::MyIK::iJnt
Definition at line 130 of file my_ik.hpp.
init_w_h
std::vector<double> MyIK::MyIK::init_w_h private
Definition at line 83 of file my_ik.hpp.
initialized
bool MyIK::MyIK::initialized private
Definition at line 29 of file my_ik.hpp.
jacsolver
std::unique_ptr<KDL::ChainJntToJacSolver> MyIK::MyIK::jacsolver private
Definition at line 53 of file my_ik.hpp.
lb
KDL::JntArray MyIK::MyIK::lb private
Definition at line 32 of file my_ik.hpp.
mtx_
std::mutex MyIK::MyIK::mtx_ private
Definition at line 40 of file my_ik.hpp.
myIKs
std::vector<std::shared_ptr<MyIK> > MyIK::MyIK::myIKs
Definition at line 127 of file my_ik.hpp.
nAddObj
int MyIK::MyIK::nAddObj = 2 private
Definition at line 87 of file my_ik.hpp.
nameJnt
std::vector<std::string> MyIK::MyIK::nameJnt private
Definition at line 59 of file my_ik.hpp.
nJnt
unsigned int MyIK::MyIK::nJnt private
Definition at line 51 of file my_ik.hpp.
nRobot
const int MyIK::MyIK::nRobot
Definition at line 133 of file my_ik.hpp.
nSeg
unsigned int MyIK::MyIK::nSeg private
Definition at line 51 of file my_ik.hpp.
nState
int MyIK::MyIK::nState = 0
Definition at line 129 of file my_ik.hpp.
poseFeedbackDisabled
bool MyIK::MyIK::poseFeedbackDisabled = false private
Definition at line 63 of file my_ik.hpp.
primalVariable
Eigen::Matrix<double, Eigen::Dynamic, 1> MyIK::MyIK::primalVariable private
Definition at line 88 of file my_ik.hpp.
progress
int MyIK::MyIK::progress private
Definition at line 48 of file my_ik.hpp.
q_rest
std::vector<KDL::JntArray> MyIK::MyIK::q_rest private
Definition at line 85 of file my_ik.hpp.
solutions
std::vector<KDL::JntArray> MyIK::MyIK::solutions private
Definition at line 41 of file my_ik.hpp.
solvetype
SolveType MyIK::MyIK::solvetype private
Definition at line 36 of file my_ik.hpp.
T_base_world
Affine3d MyIK::MyIK::T_base_world private
Definition at line 57 of file my_ik.hpp.
types
std::vector<BasicJointType> MyIK::MyIK::types private
Definition at line 38 of file my_ik.hpp.
ub
KDL::JntArray MyIK::MyIK::ub private
Definition at line 32 of file my_ik.hpp.
vb
KDL::JntArray MyIK::MyIK::vb private
Definition at line 32 of file my_ik.hpp.
w_h
std::vector<double> MyIK::MyIK::w_h private
Definition at line 83 of file my_ik.hpp.
The documentation for this class was generated from the following files:
my_ik.hpp
my_ik.cpp