OpenHRC: JoyTopicInterface Class Reference
JoyTopicInterface Class Reference
#include <joy_topic_interface.hpp>
Public Member Functions
void updateTargetPose (KDL::Frame &pose, KDL::Twist &twist) override
void initInterface () override
Public Member Functions inherited from TwistTopicInterface
void updateTargetPose (KDL::Frame &pose, KDL::Twist &twist) override
void initInterface () override
void resetInterface () override
Interface (std::shared_ptr< CartController > controller)
Public Member Functions inherited from Interface
Interface (std::shared_ptr< CartController > controller)
virtual void feedback (const KDL::Frame &targetPos, const KDL::Twist &targetTwist)
std::string getTargetName ()
double getTargetDistance ()
TaskState getTaskState ()
Protected Member Functions
void cbJoy (const sensor_msgs::Joy::ConstPtr &msg)
void setSubscriber () override
Protected Member Functions inherited from TwistTopicInterface
void cbTwist (const geometry_msgs::Twist::ConstPtr &msg)
void setPoseFromTwistMsg (const geometry_msgs::Twist &twist_msg, KDL::Frame &pos, KDL::Twist &twist)
Protected Member Functions inherited from Interface
void reset ()
Protected Attributes
std::string stateTopicName = "/spacenav/joy"
std::string stateFrameId = "world"
Protected Attributes inherited from TwistTopicInterface
bool _flagTopic = false
TransformUtility trans
Affine3d T
Matrix3d R
bool isFirst = true
std::mutex mtx_topic
ohrc_msgs::State state
std::string stateTopicName = "/cmd_vel"
std::string stateFrameId = "world"
Protected Attributes inherited from Interface
ros::NodeHandle n
double dt
std::shared_ptr< CartController > controller
ros::TransportHints th = ros::TransportHints().tcpNoDelay(true)
TaskState taskState = TaskState::Initial
std::string targetName
double targetDistance = 0.0
Private Attributes
ros::Subscriber subJoy
sensor_msgs::Joy _joy
double gain_h = 0.1
double gain_r = 0.1
Additional Inherited Members
Public Attributes inherited from Interface
int targetIdx = -1
int nCompletedTask = 0
bool blocked = false
Detailed Description
Definition at line 7 of file joy_topic_interface.hpp.
Member Function Documentation
cbJoy()
void JoyTopicInterface::cbJoy (const sensor_msgs::Joy::ConstPtr & msg) protected
Definition at line 14 of file joy_topic_interface.cpp.
References TwistTopicInterface::_flagTopic, _joy, and TwistTopicInterface::mtx_topic.
Referenced by setSubscriber().
initInterface()
void JoyTopicInterface::initInterface () override virtual
Reimplemented from Interface.
Definition at line 3 of file joy_topic_interface.cpp.
References gain_h, gain_r, TwistTopicInterface::initInterface(), and Interface::n.
setSubscriber()
void JoyTopicInterface::setSubscriber () override protected virtual
Reimplemented from TwistTopicInterface.
Definition at line 10 of file joy_topic_interface.cpp.
References cbJoy(), Interface::n, stateTopicName, subJoy, and Interface::th.
updateTargetPose()
void JoyTopicInterface::updateTargetPose (KDL::Frame & pose, KDL::Twist & twist) override virtual
Reimplemented from Interface.
Definition at line 20 of file joy_topic_interface.cpp.
References TwistTopicInterface::_flagTopic, _joy, gain_h, gain_r, TwistTopicInterface::mtx_topic, Interface::reset(), and TwistTopicInterface::setPoseFromTwistMsg().
Member Data Documentation
_joy
sensor_msgs::Joy JoyTopicInterface::_joy private
Definition at line 9 of file joy_topic_interface.hpp.
Referenced by cbJoy(), and updateTargetPose().
gain_h
double JoyTopicInterface::gain_h = 0.1 private
Definition at line 11 of file joy_topic_interface.hpp.
Referenced by initInterface(), and updateTargetPose().
gain_r
double JoyTopicInterface::gain_r = 0.1 private
Definition at line 11 of file joy_topic_interface.hpp.
Referenced by initInterface(), and updateTargetPose().
stateFrameId
std::string JoyTopicInterface::stateFrameId = "world" protected
Definition at line 14 of file joy_topic_interface.hpp.
stateTopicName
std::string JoyTopicInterface::stateTopicName = "/spacenav/joy" protected
Definition at line 14 of file joy_topic_interface.hpp.
Referenced by setSubscriber().
subJoy
ros::Subscriber JoyTopicInterface::subJoy private
Definition at line 8 of file joy_topic_interface.hpp.
Referenced by setSubscriber().
The documentation for this class was generated from the following files:
joy_topic_interface.hpp
joy_topic_interface.cpp