OpenHRC: JointTrajectoryController Class Reference
JointTrajectoryController Class Reference
#include <joint_trajectory_controller.hpp>
Public Member Functions
virtual void initInterface () override
virtual void updateTargetPose (KDL::Frame &pose, KDL::Twist &twist) override
Interface (std::shared_ptr< CartController > controller)
Public Member Functions inherited from Interface
Interface (std::shared_ptr< CartController > controller)
virtual void resetInterface ()
virtual void feedback (const KDL::Frame &targetPos, const KDL::Twist &targetTwist)
std::string getTargetName ()
double getTargetDistance ()
TaskState getTaskState ()
Protected Member Functions
void cbJointTrajectory (const moveit_msgs::MoveGroupActionResult::ConstPtr &msg)
virtual void setSubscriber ()
Protected Member Functions inherited from Interface
void reset ()
Protected Attributes
std::mutex mtx_joint
ros::Subscriber trjSubscriber
trajectory_msgs::JointTrajectory _jointTrj
moveit_msgs::CartesianTrajectory _cartTrj
bool _start = true
Protected Attributes inherited from Interface
ros::NodeHandle n
const double dt
std::shared_ptr< CartController > controller
ros::TransportHints th = ros::TransportHints().tcpNoDelay(true)
TaskState taskState = TaskState::Initial
std::string targetName
double targetDistance = 0.0
Additional Inherited Members
Public Attributes inherited from Interface
int targetIdx = -1
int nCompletedTask = 0
bool blocked = false
Detailed Description
Definition at line 10 of file joint_trajectory_controller.hpp.
Member Function Documentation
cbJointTrajectory()
void JointTrajectoryController::cbJointTrajectory (const moveit_msgs::MoveGroupActionResult::ConstPtr & msg) protected
Definition at line 11 of file joint_trajectory_controller.cpp.
References _cartTrj, _jointTrj, _start, Interface::controller, std_utility::exist_in(), mtx_joint, and tf2::toMsg().
Referenced by setSubscriber().
initInterface()
void JointTrajectoryController::initInterface () override virtual
Reimplemented from Interface.
Definition at line 3 of file joint_trajectory_controller.cpp.
References setSubscriber().
Interface()
Interface::Interface inline
Definition at line 26 of file interface.hpp.
setSubscriber()
void JointTrajectoryController::setSubscriber () protected virtual
Definition at line 7 of file joint_trajectory_controller.cpp.
References cbJointTrajectory(), Interface::n, Interface::th, and trjSubscriber.
Referenced by initInterface().
updateTargetPose()
void JointTrajectoryController::updateTargetPose (KDL::Frame & pose, KDL::Twist & twist) override virtual
Reimplemented from Interface.
Definition at line 45 of file joint_trajectory_controller.cpp.
References _cartTrj, _jointTrj, _start, Interface::controller, tf2::fromMsg(), and mtx_joint.
Member Data Documentation
_cartTrj
moveit_msgs::CartesianTrajectory JointTrajectoryController::_cartTrj protected
Definition at line 16 of file joint_trajectory_controller.hpp.
Referenced by cbJointTrajectory(), and updateTargetPose().
_jointTrj
trajectory_msgs::JointTrajectory JointTrajectoryController::_jointTrj protected
Definition at line 15 of file joint_trajectory_controller.hpp.
Referenced by cbJointTrajectory(), and updateTargetPose().
_start
bool JointTrajectoryController::_start = true protected
Definition at line 21 of file joint_trajectory_controller.hpp.
Referenced by cbJointTrajectory(), and updateTargetPose().
mtx_joint
std::mutex JointTrajectoryController::mtx_joint protected
Definition at line 12 of file joint_trajectory_controller.hpp.
Referenced by cbJointTrajectory(), and updateTargetPose().
trjSubscriber
ros::Subscriber JointTrajectoryController::trjSubscriber protected
Definition at line 13 of file joint_trajectory_controller.hpp.
Referenced by setSubscriber().
The documentation for this class was generated from the following files:
joint_trajectory_controller.hpp
joint_trajectory_controller.cpp