OpenHRC: BodyStateVisualizer Class Reference
BodyStateVisualizer Class Reference
Public Member Functions
BodyStateVisualizer ()
int run ()
Private Member Functions
void cbBodyState (const ohrc_msgs::BodyState::ConstPtr &msg)
void publishBodyStateMarker (const ohrc_msgs::BodyState &bodyState)
Private Attributes
ros::NodeHandle n
ros::Subscriber sub
ros::Publisher bodyStateMarkerPublisher
ohrc_msgs::BodyState _bodyState
std::mutex mtx
Detailed Description
Definition at line 6 of file body_state_visualizer.cpp.
Constructor & Destructor Documentation
BodyStateVisualizer()
BodyStateVisualizer::BodyStateVisualizer ()
Definition at line 23 of file body_state_visualizer.cpp.
References bodyStateMarkerPublisher, cbBodyState(), n, and sub.
Member Function Documentation
cbBodyState()
void BodyStateVisualizer::cbBodyState (const ohrc_msgs::BodyState::ConstPtr & msg) private
Definition at line 28 of file body_state_visualizer.cpp.
References _bodyState, and mtx.
Referenced by BodyStateVisualizer().
publishBodyStateMarker()
void BodyStateVisualizer::publishBodyStateMarker (const ohrc_msgs::BodyState & bodyState) private
Definition at line 33 of file body_state_visualizer.cpp.
References bodyStateMarkerPublisher.
Referenced by run().
run()
int BodyStateVisualizer::run ()
Definition at line 66 of file body_state_visualizer.cpp.
References _bodyState, mtx, and publishBodyStateMarker().
Referenced by main().
Member Data Documentation
_bodyState
ohrc_msgs::BodyState BodyStateVisualizer::_bodyState private
Definition at line 11 of file body_state_visualizer.cpp.
Referenced by cbBodyState(), and run().
bodyStateMarkerPublisher
ros::Publisher BodyStateVisualizer::bodyStateMarkerPublisher private
Definition at line 9 of file body_state_visualizer.cpp.
Referenced by BodyStateVisualizer(), and publishBodyStateMarker().
mtx
std::mutex BodyStateVisualizer::mtx private
Definition at line 13 of file body_state_visualizer.cpp.
Referenced by cbBodyState(), and run().
n
ros::NodeHandle BodyStateVisualizer::n private
Definition at line 7 of file body_state_visualizer.cpp.
Referenced by BodyStateVisualizer().
sub
ros::Subscriber BodyStateVisualizer::sub private
Definition at line 8 of file body_state_visualizer.cpp.
Referenced by BodyStateVisualizer().
The documentation for this class was generated from the following file:
body_state_visualizer.cpp