OpenHRC: PositionFeedbackController Class Reference
PositionFeedbackController Class Reference
#include <position_feedback_controller.hpp>
Public Member Functions
virtual void updateTargetPose (KDL::Frame &pose, KDL::Twist &twist) override
virtual void initInterface () override
Interface (const std::shared_ptr< CartController > controller)
Public Member Functions inherited from Interface
Interface (const std::shared_ptr< CartController > controller)
virtual void resetInterface ()
virtual void feedback (const KDL::Frame &targetPos, const KDL::Twist &targetTwist)
std::string getTargetName ()
double getTargetDistance ()
TaskState getTaskState ()
VectorXd getTargetError ()
Private Member Functions
VectorXd PIControl (const KDL::Frame &frame, const KDL::Frame &pose, const KDL::Twist &twist)
VectorXd PIControl (const VectorXd &e, const KDL::Twist &twist)
VectorXd adaptivePIControl (const KDL::Frame &frame, const KDL::Frame &pose, const KDL::Twist &twist)
VectorXd adaptivePIControl (const VectorXd &e, const KDL::Twist &twist)
VectorXd forceFeedbackControl (const KDL::Frame &frame, const KDL::Frame &pose, const VectorXd f)
VectorXd forceFeedbackControl (const VectorXd &e, const VectorXd f)
Private Attributes
VectorXd x
VectorXd xd
std::vector< double > t0_f
Additional Inherited Members
Public Attributes inherited from Interface
int targetIdx = -1
int nCompletedTask = 0
bool blocked = false
Protected Member Functions inherited from Interface
void reset ()
void getTopicAndFrameName (std::string DefaultStateTopicName, std::string DefaultStateFrameId)
Protected Attributes inherited from Interface
ros::NodeHandle n
const double dt
std::shared_ptr< CartController > controller
ros::TransportHints th = ros::TransportHints().tcpNoDelay(true)
TaskState taskState = TaskState::Initial
std::string targetName
double targetDistance = 0.0
VectorXd e
std::string stateTopicName = "/state"
std::string stateFrameId = "world"
Detailed Description
Definition at line 6 of file position_feedback_controller.hpp.
Member Function Documentation
adaptivePIControl() [1/2]
VectorXd PositionFeedbackController::adaptivePIControl (const KDL::Frame & frame, const KDL::Frame & pose, const KDL::Twist & twist) private
adaptivePIControl() [2/2]
VectorXd PositionFeedbackController::adaptivePIControl (const VectorXd & e, const KDL::Twist & twist) private
forceFeedbackControl() [1/2]
VectorXd PositionFeedbackController::forceFeedbackControl (const KDL::Frame & frame, const KDL::Frame & pose, const VectorXd f) private
forceFeedbackControl() [2/2]
VectorXd PositionFeedbackController::forceFeedbackControl (const VectorXd & e, const VectorXd f) private
initInterface()
void PositionFeedbackController::initInterface () override virtual
Reimplemented from Interface.
Definition at line 3 of file position_feedback_controller.cpp.
References t0_f.
Interface()
Interface::Interface inline
Definition at line 37 of file interface.hpp.
PIControl() [1/2]
VectorXd PositionFeedbackController::PIControl (const KDL::Frame & frame, const KDL::Frame & pose, const KDL::Twist & twist) private
Definition at line 25 of file position_feedback_controller.cpp.
Referenced by updateTargetPose().
PIControl() [2/2]
VectorXd PositionFeedbackController::PIControl (const VectorXd & e, const KDL::Twist & twist) private
Definition at line 42 of file position_feedback_controller.cpp.
References Interface::e.
updateTargetPose()
void PositionFeedbackController::updateTargetPose (KDL::Frame & pose, KDL::Twist & twist) override virtual
Reimplemented from Interface.
Definition at line 7 of file position_feedback_controller.cpp.
References Interface::controller, Interface::e, MyIK::getCartError(), and PIControl().
Member Data Documentation
t0_f
std::vector<double> PositionFeedbackController::t0_f private
Definition at line 16 of file position_feedback_controller.hpp.
Referenced by initInterface().
x
VectorXd PositionFeedbackController::x private
Definition at line 7 of file position_feedback_controller.hpp.
xd
VectorXd PositionFeedbackController::xd private
Definition at line 7 of file position_feedback_controller.hpp.
The documentation for this class was generated from the following files:
position_feedback_controller.hpp
position_feedback_controller.cpp