OpenHRC: StateTopicInterface Class Reference
StateTopicInterface Class Reference
#include <state_topic_interface.hpp>
Public Member Functions
void updateTargetPose (KDL::Frame &pose, KDL::Twist &twist) override
void initInterface () override
Interface (std::shared_ptr< CartController > controller)
Public Member Functions inherited from Interface
Interface (std::shared_ptr< CartController > controller)
virtual void resetInterface ()
virtual void feedback (const KDL::Frame &targetPos, const KDL::Twist &targetTwist)
std::string getTargetName ()
double getTargetDistance ()
TaskState getTaskState ()
Protected Member Functions
void cbState (const ohrc_msgs::State::ConstPtr &msg)
virtual void modifyTargetState (ohrc_msgs::State &state)
virtual void setSubscriber ()
void getTargetState (const ohrc_msgs::State &state, KDL::Frame &pos, KDL::Twist &twist)
Protected Member Functions inherited from Interface
void reset ()
Protected Attributes
ros::Subscriber subState
Affine3d T_state_base
double k_trans = 1.0
TransformUtility trans
ros::TransportHints th = ros::TransportHints().tcpNoDelay(true)
Affine3d T
Affine3d T_start
Affine3d T_state_start
bool isFirst = true
std::mutex mtx_state
ohrc_msgs::State _state
bool _flagTopic = false
std::string stateTopicName = "/state"
std::string stateFrameId = "world"
Protected Attributes inherited from Interface
ros::NodeHandle n
double dt
std::shared_ptr< CartController > controller
ros::TransportHints th = ros::TransportHints().tcpNoDelay(true)
TaskState taskState = TaskState::Initial
std::string targetName
double targetDistance = 0.0
Additional Inherited Members
Public Attributes inherited from Interface
int targetIdx = -1
int nCompletedTask = 0
bool blocked = false
Detailed Description
Definition at line 7 of file state_topic_interface.hpp.
Member Function Documentation
cbState()
void StateTopicInterface::cbState (const ohrc_msgs::State::ConstPtr & msg) protected
Definition at line 16 of file state_topic_interface.cpp.
References _state, and mtx_state.
Referenced by setSubscriber().
getTargetState()
void StateTopicInterface::getTargetState (const ohrc_msgs::State & state, KDL::Frame & pos, KDL::Twist & twist) protected
Definition at line 21 of file state_topic_interface.cpp.
References Interface::controller, tf2::fromMsg(), isFirst, k_trans, Interface::reset(), T, T_start, T_state_base, and T_state_start.
Referenced by updateTargetPose(), and XrBodyInterface::updateTargetPose().
initInterface()
void StateTopicInterface::initInterface () override virtual
Reimplemented from Interface.
Reimplemented in XrBodyInterface.
Definition at line 3 of file state_topic_interface.cpp.
References Interface::controller, k_trans, Interface::n, setSubscriber(), stateFrameId, and T_state_base.
Referenced by OmegaInterface::initInterface(), and XrBodyInterface::initInterface().
Interface()
Interface::Interface inline
Definition at line 26 of file interface.hpp.
modifyTargetState()
virtual void StateTopicInterface::modifyTargetState (ohrc_msgs::State & state) inline protected virtual
Reimplemented in OmegaInterface.
Definition at line 27 of file state_topic_interface.hpp.
Referenced by updateTargetPose().
setSubscriber()
void StateTopicInterface::setSubscriber () protected virtual
Reimplemented in XrBodyInterface.
Definition at line 12 of file state_topic_interface.cpp.
References cbState(), Interface::n, stateTopicName, subState, and th.
Referenced by initInterface().
updateTargetPose()
void StateTopicInterface::updateTargetPose (KDL::Frame & pose, KDL::Twist & twist) override virtual
Reimplemented from Interface.
Reimplemented in XrBodyInterface.
Definition at line 63 of file state_topic_interface.cpp.
References _state, getTargetState(), modifyTargetState(), and mtx_state.
Member Data Documentation
_flagTopic
bool StateTopicInterface::_flagTopic = false protected
Definition at line 22 of file state_topic_interface.hpp.
Referenced by XrBodyInterface::cbBody(), and XrBodyInterface::updateTargetPose().
_state
ohrc_msgs::State StateTopicInterface::_state protected
Definition at line 21 of file state_topic_interface.hpp.
Referenced by cbState(), and updateTargetPose().
isFirst
bool StateTopicInterface::isFirst = true protected
Definition at line 18 of file state_topic_interface.hpp.
Referenced by getTargetState(), and XrBodyInterface::resetInterface().
k_trans
double StateTopicInterface::k_trans = 1.0 protected
Definition at line 11 of file state_topic_interface.hpp.
Referenced by getTargetState(), and initInterface().
mtx_state
std::mutex StateTopicInterface::mtx_state protected
Definition at line 20 of file state_topic_interface.hpp.
Referenced by XrBodyInterface::cbBody(), cbState(), updateTargetPose(), and XrBodyInterface::updateTargetPose().
stateFrameId
std::string StateTopicInterface::stateFrameId = "world" protected
Definition at line 24 of file state_topic_interface.hpp.
Referenced by OmegaInterface::initInterface(), initInterface(), and XrBodyInterface::initInterface().
stateTopicName
std::string StateTopicInterface::stateTopicName = "/state" protected
Definition at line 24 of file state_topic_interface.hpp.
Referenced by OmegaInterface::initInterface(), XrBodyInterface::initInterface(), setSubscriber(), and XrBodyInterface::setSubscriber().
subState
ros::Subscriber StateTopicInterface::subState protected
Definition at line 9 of file state_topic_interface.hpp.
Referenced by setSubscriber().
T
Affine3d StateTopicInterface::T protected
Definition at line 17 of file state_topic_interface.hpp.
Referenced by getTargetState().
T_start
Affine3d StateTopicInterface::T_start protected
Definition at line 17 of file state_topic_interface.hpp.
Referenced by getTargetState().
T_state_base
Affine3d StateTopicInterface::T_state_base protected
Definition at line 10 of file state_topic_interface.hpp.
Referenced by OmegaInterface::feedback(), getTargetState(), and initInterface().
T_state_start
Affine3d StateTopicInterface::T_state_start protected
Definition at line 17 of file state_topic_interface.hpp.
Referenced by getTargetState().
th
ros::TransportHints StateTopicInterface::th = ros::TransportHints().tcpNoDelay(true) protected
Definition at line 15 of file state_topic_interface.hpp.
Referenced by setSubscriber(), and XrBodyInterface::setSubscriber().
trans
TransformUtility StateTopicInterface::trans protected
Definition at line 13 of file state_topic_interface.hpp.
The documentation for this class was generated from the following files:
state_topic_interface.hpp
state_topic_interface.cpp