OpenHRC: CartTrajectoryController Class Reference
CartTrajectoryController Class Reference
#include <cart_trajectory_controller.hpp>
Public Member Functions
virtual void initInterface () override
virtual void resetInterface () override
virtual void updateTargetPose (KDL::Frame &pose, KDL::Twist &twist) override
Interface (const std::shared_ptr< CartController > controller)
Public Member Functions inherited from Interface
Interface (const std::shared_ptr< CartController > controller)
virtual void feedback (const KDL::Frame &targetPos, const KDL::Twist &targetTwist)
std::string getTargetName ()
double getTargetDistance ()
TaskState getTaskState ()
VectorXd getTargetError ()
Protected Member Functions
void cbCartTrajectory (const moveit_msgs::CartesianTrajectory::ConstPtr &msg)
virtual void setSubscriber ()
virtual moveit_msgs::CartesianTrajectory interpolateTrajectory (const moveit_msgs::CartesianTrajectory &trj)
virtual void modifyTrajectory (moveit_msgs::CartesianTrajectory &trj)
Protected Member Functions inherited from Interface
void reset ()
void getTopicAndFrameName (std::string DefaultStateTopicName, std::string DefaultStateFrameId)
Protected Attributes
std::mutex mtx_cart
ros::Subscriber trjSubscriber
bool relative = true
moveit_msgs::CartesianTrajectory _trj
Protected Attributes inherited from Interface
ros::NodeHandle n
const double dt
std::shared_ptr< CartController > controller
ros::TransportHints th = ros::TransportHints().tcpNoDelay(true)
TaskState taskState = TaskState::Initial
std::string targetName
double targetDistance = 0.0
VectorXd e
std::string stateTopicName = "/state"
std::string stateFrameId = "world"
Private Attributes
Affine3d T_init
int i = 0
bool start = true
bool _newTrj = false
Additional Inherited Members
Public Attributes inherited from Interface
int targetIdx = -1
int nCompletedTask = 0
bool blocked = false
Detailed Description
Definition at line 9 of file cart_trajectory_controller.hpp.
Member Function Documentation
cbCartTrajectory()
void CartTrajectoryController::cbCartTrajectory (const moveit_msgs::CartesianTrajectory::ConstPtr & msg) protected
Definition at line 15 of file cart_trajectory_controller.cpp.
References _newTrj, _trj, Interface::controller, Interface::dt, interpolateTrajectory(), modifyTrajectory(), mtx_cart, relative, tf2::toMsg(), and promp_trajectory_publisher::trj.
Referenced by setSubscriber().
initInterface()
void CartTrajectoryController::initInterface () override virtual
Reimplemented from Interface.
Reimplemented in SwitchingInterface< MarkerInterface, CartTrajectoryController >.
Definition at line 3 of file cart_trajectory_controller.cpp.
References Interface::controller, Interface::n, relative, setSubscriber(), and T_init.
Interface()
Interface::Interface inline
Definition at line 37 of file interface.hpp.
interpolateTrajectory()
virtual moveit_msgs::CartesianTrajectory CartTrajectoryController::interpolateTrajectory (const moveit_msgs::CartesianTrajectory & trj) inline protected virtual
Reimplemented in CartTrajectoryMinjerkController.
Definition at line 25 of file cart_trajectory_controller.hpp.
References promp_trajectory_publisher::trj.
Referenced by cbCartTrajectory().
modifyTrajectory()
virtual void CartTrajectoryController::modifyTrajectory (moveit_msgs::CartesianTrajectory & trj) inline protected virtual
Definition at line 29 of file cart_trajectory_controller.hpp.
Referenced by cbCartTrajectory().
resetInterface()
void CartTrajectoryController::resetInterface () override virtual
Reimplemented from Interface.
Reimplemented in SwitchingInterface< MarkerInterface, CartTrajectoryController >.
Definition at line 101 of file cart_trajectory_controller.cpp.
References _trj, Interface::controller, start, and T_init.
setSubscriber()
void CartTrajectoryController::setSubscriber () protected virtual
Definition at line 11 of file cart_trajectory_controller.cpp.
References cbCartTrajectory(), Interface::n, Interface::th, and trjSubscriber.
Referenced by initInterface().
updateTargetPose()
void CartTrajectoryController::updateTargetPose (KDL::Frame & pose, KDL::Twist & twist) override virtual
Reimplemented from Interface.
Reimplemented in SwitchingInterface< MarkerInterface, CartTrajectoryController >.
Definition at line 34 of file cart_trajectory_controller.cpp.
References _newTrj, _trj, Interface::controller, Interface::e, tf2::fromMsg(), MyIK::getCartError(), i, mtx_cart, relative, start, T_init, and promp_trajectory_publisher::trj.
Member Data Documentation
_newTrj
bool CartTrajectoryController::_newTrj = false private
Definition at line 12 of file cart_trajectory_controller.hpp.
Referenced by cbCartTrajectory(), and updateTargetPose().
_trj
moveit_msgs::CartesianTrajectory CartTrajectoryController::_trj protected
Definition at line 19 of file cart_trajectory_controller.hpp.
Referenced by cbCartTrajectory(), resetInterface(), and updateTargetPose().
i
int CartTrajectoryController::i = 0 private
Definition at line 11 of file cart_trajectory_controller.hpp.
Referenced by CartTrajectoryMinjerkController::interpolateTrajectory(), and updateTargetPose().
mtx_cart
std::mutex CartTrajectoryController::mtx_cart protected
Definition at line 15 of file cart_trajectory_controller.hpp.
Referenced by cbCartTrajectory(), and updateTargetPose().
relative
bool CartTrajectoryController::relative = true protected
Definition at line 17 of file cart_trajectory_controller.hpp.
Referenced by cbCartTrajectory(), initInterface(), and updateTargetPose().
start
bool CartTrajectoryController::start = true private
Definition at line 12 of file cart_trajectory_controller.hpp.
Referenced by resetInterface(), and updateTargetPose().
T_init
Affine3d CartTrajectoryController::T_init private
Definition at line 10 of file cart_trajectory_controller.hpp.
Referenced by initInterface(), resetInterface(), and updateTargetPose().
trjSubscriber
ros::Subscriber CartTrajectoryController::trjSubscriber protected
Definition at line 16 of file cart_trajectory_controller.hpp.
Referenced by setSubscriber().
The documentation for this class was generated from the following files:
cart_trajectory_controller.hpp
cart_trajectory_controller.cpp