OpenHRC: CartController Class Reference
CartController Class Reference
#include <cart_controller.hpp>
Classes
struct s_cbJntState
struct s_moveInitPos
Public Member Functions
CartController ()
CartController (const std::string robot, const std::string root_frame)
CartController (const std::string robot, const std::string root_frame, const int index)
CartController (const std::string robot, const std::string hw_config, const std::string root_frame, const int index)
~CartController ()
int control ()
void update ()
Updates controller, i.e. computes the odometry and sets the new velocity commands.
void update (const ros::Time &time, const ros::Duration &period)
void starting (const ros::Time &time)
Starts controller.
void stopping (const ros::Time &time)
Stops controller.
void getIKInput (double dt, KDL::JntArray &q_cur, KDL::Frame &des_eef_pose, KDL::Twist &des_eef_vel)
void getVelocity (const KDL::Frame &frame, const KDL::Frame &prev_frame, const double &dt, KDL::Twist &twist) const
void updateCurState ()
void getState (KDL::JntArray &q_cur, KDL::JntArray &dq_cur)
void getState (KDL::JntArray &q_cur, KDL::JntArray &dq_cur, KDL::Frame &frame, KDL::Twist &twist)
void getCartState (KDL::Frame &frame, KDL::Twist &twist)
void publishDesEffPoseVel (const KDL::Frame &des_eef_pose, const KDL::Twist &des_eef_vel)
void publishCurEffPoseVel (const KDL::Frame &cur_eef_pose, const KDL::Twist &cur_eef_vel)
void getDesState (const KDL::Frame &cur_pose, const KDL::Twist &cur_vel, KDL::Frame &des_pose, KDL::Twist &des_vel)
void publishState (const KDL::Frame &pose, const KDL::Twist &vel, ros::Publisher *publisher)
void publishState (const KDL::Frame &pose, const KDL::Twist &vel, const geometry_msgs::Wrench &wrench, ros::Publisher *publisher)
void publishMarker (const KDL::JntArray q_cur)
void filterJnt (KDL::JntArray &q)
void updatePosFilterCutoff (const double posFreq)
void updateVelFilterCutoff (const double velFreq)
void updateJntFilterCutoff (const double jntFreq)
void updateFilterCutoff (const double velFreq, const double jntFreq)
void startOperation ()
void enableOperation ()
void disableOperation ()
bool getOperationEnable () const
void getInfo (std::string &chain_start, std::string &chain_end, Affine3d &T_base_root, std::shared_ptr< MyIK::MyIK > &myik)
std::string getChainStart () const
std::string getChainEnd () const
void JntToCart (const KDL::JntArray &q_in, KDL::Frame &p_out)
void JntToCart (const KDL::JntArray &q_in, const KDL::JntArray &dq_in, KDL::Frame &p_out, KDL::Twist &v_out)
void JntVelToCartVel (const KDL::JntArray &q_in, const KDL::JntArray &dq_in, KDL::Twist &v_out)
std::string getRobotNs () const
int getIndex ()
Affine3d getTransform_base (std::string target)
Affine3d getT_init () const
Affine3d getT_cur ()
Affine3d getT_root ()
Affine3d getT_base_world ()
geometry_msgs::WrenchStamped getForceEef ()
VectorXd getForceEefVec ()
unsigned int getNJnt ()
std::vector< std::string > getNameJnt ()
bool isInitialized ()
void setDesired (const KDL::Frame &des_eef_pose, const KDL::Twist &des_eef_vel)
void enablePoseFeedback ()
void disablePoseFeedback ()
Affine3d getTft_eff ()
KDL::JntArray getqRest ()
void setqRest (const KDL::JntArray &q_rest)
bool getFtFound ()
void resetPose ()
void resetFt ()
void sendPosCmd (const KDL::JntArray &q_des, const KDL::JntArray &dq_des, const double &dt)
void sendVelCmd (const KDL::JntArray &q_des, const KDL::JntArray &dq_des, const double &dt)
Public Attributes
double dt
double freq = 500.0
const double eps = 1e-6
ros::Publisher markerPublisher
ros::Publisher desStatePublisher
ros::Publisher curStatePublisher
ros::Publisher jntCmdPublisher
std::mutex mtx
bool flagJntState = false
Protected Member Functions
void cbJntState (const sensor_msgs::JointState::ConstPtr &msg)
void cbArmMarker (const visualization_msgs::MarkerArray::ConstPtr &msg)
void cbForce (const geometry_msgs::WrenchStamped::ConstPtr &msg)
void initDesWithJnt (const KDL::JntArray &q_init)
virtual void initWithJnt (const KDL::JntArray &q_init)
void filterDesEffPoseVel (KDL::Frame &des_eef_pose, KDL::Twist &des_eef_vel)
int moveInitPos (const KDL::JntArray &q_cur, const std::vector< std::string > nameJnt, std::vector< int > idxSegJnt)
void sendPositionCmd (const VectorXd &q_des)
void sendVelocityCmd (const VectorXd &dq_des)
void sendVelocityCmd (const VectorXd &q_des, const VectorXd &dq_des, const KDL::JntArray &q_cur, const bool &lastLoop)
void sendTrajectoryCmd (const VectorXd &q_des, const double &T)
void sendTrajectoryCmd (const VectorXd &q_des, const VectorXd &dq_des, const double &T)
void sendTrajectoryActionCmd (const VectorXd &q_des, const double &T)
void sendTrajectoryActionCmd (const VectorXd &q_des, const VectorXd &dq_des, const double &T)
void getTrajectoryCmd (const VectorXd &q_des, const double &T, trajectory_msgs::JointTrajectory &cmd_trj)
void getTrajectoryCmd (const VectorXd &q_des, const VectorXd &dq_des, const double &T, trajectory_msgs::JointTrajectory &cmd_trj)
Protected Attributes
SolverType solver
ControllerType controller
PublisherType publisher
ros::NodeHandle nh
ros::Subscriber jntStateSubscriber
ros::Subscriber userArmMarker
ros::Subscriber subForce
ros::TransportHints th = ros::TransportHints().tcpNoDelay(true)
std::vector< bool * > subFlagPtrs
bool flagEffPose = false
Matrix3d _userManipU = Matrix3d::Identity()
bool flagArmMarker = false
bool useManipOpt = false
int num_samples
double timeout
Affine3d T_init
Affine3d Tft_eff
unsigned int nJnt
const unsigned int m = 6
std::vector< std::string > nameJnt
KDL::Frame _des_eef_pose
KDL::Frame _current_eef_pose
KDL::Twist _des_eef_vel
geometry_msgs::WrenchStamped _force
bool flagForce = false
bool _disable = true
bool _passThrough = false
KDL::JntArray _q_cur
KDL::JntArray _dq_cur
KDL::JntArray _q_cur_t
KDL::JntArray _dq_cur_t
std::vector< butterworth > posFilter
std::vector< butterworth > velFilter
std::vector< butterworth > jntFilter
TransformUtility trans
tf2_ros::TransformBroadcaster br
std::unique_ptr< KDL::ChainIkSolverVel_pinv > vik_solver_ptr
std::unique_ptr< KDL::ChainIkSolverPos_NR_JL > kdl_solver_ptr
std::unique_ptr< TRAC_IK::TRAC_IK > tracik_solver_ptr
std::unique_ptr< KDL::ChainFkSolverPos_recursive > fk_solver_ptr
KDL::Chain chain
std::vector< KDL::Segment > chain_segs
std::shared_ptr< MyIK::MyIK > myik_solver_ptr
std::string root_frame
std::string chain_start
std::string chain_end
std::string urdf_param
std::string robot_ns = ""
std::string hw_config_ns = ""
Affine3d T_base_root
const int index = 0
Private Member Functions
void init (std::string robot)
void init (std::string robot, std::string hw_config)
bool getInitParam ()
bool resetService (std_srvs::Empty::Request &req, std_srvs::Empty::Response &res)
Static Private Member Functions
static void signal_handler (int signum)
Private Attributes
ros::CallbackQueue queue
boost::shared_ptr< ros::AsyncSpinner > spinner
boost::shared_ptr< ros::AsyncSpinner > spinner_
ros::NodeHandle nh_
ros::Publisher pubEefForce
std::mutex mtx_q
KDL::Frame des_eef_pose
KDL::Frame current_eef_pose
KDL::Twist des_eef_vel
KDL::JntArray q_cur
KDL::JntArray dq_cur
std_msgs::Float64MultiArray cmd
Matrix3d userManipU
int rc
ros::ServiceClient client
struct CartController::s_cbJntState s_cbJntState
struct CartController::s_moveInitPos s_moveInitPos
std::vector< double > _q_init_expect
std::string initPoseFrame
std::vector< double > initPose
std::string publisherTopicName
ros::ServiceServer service
bool initialized = false
KDL::JntArray q_rest
ros::Time prev_time = ros::Time::now()
bool ftFound = false
Detailed Description
Definition at line 36 of file cart_controller.hpp.
Constructor & Destructor Documentation
CartController() [1/4]
CartController::CartController ()
Definition at line 16 of file cart_controller.cpp.
References init(), nh, and root_frame.
CartController() [2/4]
CartController::CartController (const std::string robot, const std::string root_frame)
Definition at line 12 of file cart_controller.cpp.
References init().
CartController() [3/4]
CartController::CartController (const std::string robot, const std::string root_frame, const int index)
Definition at line 8 of file cart_controller.cpp.
References init().
CartController() [4/4]
CartController::CartController (const std::string robot, const std::string hw_config, const std::string root_frame, const int index)
Definition at line 3 of file cart_controller.cpp.
References init().
~CartController()
CartController::~CartController ()
Definition at line 232 of file cart_controller.cpp.
Member Function Documentation
cbArmMarker()
void CartController::cbArmMarker (const visualization_msgs::MarkerArray::ConstPtr & msg) protected
Definition at line 348 of file cart_controller.cpp.
References _userManipU, flagArmMarker, tf2::fromMsg(), ArmMarker::ManipulabilityEllipsoid, and mtx.
Referenced by init().
cbForce()
void CartController::cbForce (const geometry_msgs::WrenchStamped::ConstPtr & msg) protected
Definition at line 363 of file cart_controller.cpp.
References _force, chain_end, flagForce, mtx, pubEefForce, robot_ns, Tft_eff, and geometry_msgs_utility::transformFT().
Referenced by init().
cbJntState()
void CartController::cbJntState (const sensor_msgs::JointState::ConstPtr & msg) protected
Definition at line 296 of file cart_controller.cpp.
References _dq_cur, _q_cur, chain_segs, dq_cur, flagJntState, initDesWithJnt(), initialized, initWithJnt(), CartController::s_cbJntState::isFirst, moveInitPos(), mtx_q, nameJnt, nJnt, and q_cur.
Referenced by init().
control()
int CartController::control ()
Definition at line 861 of file cart_controller.cpp.
References freq, starting(), stopping(), and update().
disableOperation()
void CartController::disableOperation () inline
Definition at line 243 of file cart_controller.hpp.
disablePoseFeedback()
void CartController::disablePoseFeedback () inline
Definition at line 342 of file cart_controller.hpp.
Referenced by getDesState().
enableOperation()
void CartController::enableOperation () inline
Definition at line 239 of file cart_controller.hpp.
enablePoseFeedback()
void CartController::enablePoseFeedback () inline
Definition at line 338 of file cart_controller.hpp.
Referenced by getDesState().
filterDesEffPoseVel()
void CartController::filterDesEffPoseVel (KDL::Frame & des_eef_pose, KDL::Twist & des_eef_vel) protected
Definition at line 577 of file cart_controller.cpp.
References des_eef_vel, and velFilter.
filterJnt()
void CartController::filterJnt (KDL::JntArray & q)
Definition at line 856 of file cart_controller.cpp.
References jntFilter, and nJnt.
Referenced by update().
getCartState()
void CartController::getCartState (KDL::Frame & frame, KDL::Twist & twist) inline
Definition at line 215 of file cart_controller.hpp.
getChainEnd()
std::string CartController::getChainEnd () const inline
Definition at line 260 of file cart_controller.hpp.
getChainStart()
std::string CartController::getChainStart () const inline
Definition at line 256 of file cart_controller.hpp.
getDesState()
void CartController::getDesState (const KDL::Frame & cur_pose, const KDL::Twist & cur_vel, KDL::Frame & des_pose, KDL::Twist & des_vel)
Definition at line 687 of file cart_controller.cpp.
References _des_eef_pose, _des_eef_vel, _disable, _passThrough, disablePoseFeedback(), enablePoseFeedback(), mtx, and promp_trajectory_demo::T.
Referenced by getIKInput().
getForceEef()
geometry_msgs::WrenchStamped CartController::getForceEef () inline
Definition at line 310 of file cart_controller.hpp.
References mtx.
getForceEefVec()
VectorXd CartController::getForceEefVec () inline
Definition at line 315 of file cart_controller.hpp.
References tf2::fromMsg().
getFtFound()
bool CartController::getFtFound () inline
Definition at line 358 of file cart_controller.hpp.
getIKInput()
void CartController::getIKInput (double dt, KDL::JntArray & q_cur, KDL::Frame & des_eef_pose, KDL::Twist & des_eef_vel)
Definition at line 660 of file cart_controller.cpp.
References des_eef_pose, des_eef_vel, dq_cur, getDesState(), getState(), publishCurEffPoseVel(), publishDesEffPoseVel(), and q_cur.
Referenced by update().
getIndex()
int CartController::getIndex () inline
Definition at line 280 of file cart_controller.hpp.
getInfo()
void CartController::getInfo (std::string & chain_start, std::string & chain_end, Affine3d & T_base_root, std::shared_ptr< MyIK::MyIK > & myik) inline
Definition at line 250 of file cart_controller.hpp.
getInitParam()
bool CartController::getInitParam () private
Definition at line 140 of file cart_controller.cpp.
References chain_end, chain_start, controller, freq, hw_config_ns, initPose, initPoseFrame, nh, publisher, publisherTopicName, root_frame, solver, and useManipOpt.
Referenced by init().
getNameJnt()
std::vector<std::string> CartController::getNameJnt () inline
Definition at line 323 of file cart_controller.hpp.
getNJnt()
unsigned int CartController::getNJnt () inline
Definition at line 319 of file cart_controller.hpp.
getOperationEnable()
bool CartController::getOperationEnable () const inline
Definition at line 247 of file cart_controller.hpp.
Referenced by publishState().
getqRest()
KDL::JntArray CartController::getqRest () inline
Definition at line 350 of file cart_controller.hpp.
getRobotNs()
std::string CartController::getRobotNs () const inline
Definition at line 276 of file cart_controller.hpp.
getState() [1/2]
void CartController::getState (KDL::JntArray & q_cur, KDL::JntArray & dq_cur) inline
Definition at line 202 of file cart_controller.hpp.
Referenced by getIKInput().
getState() [2/2]
void CartController::getState (KDL::JntArray & q_cur, KDL::JntArray & dq_cur, KDL::Frame & frame, KDL::Twist & twist) inline
Definition at line 208 of file cart_controller.hpp.
getT_base_world()
Affine3d CartController::getT_base_world () inline
Definition at line 306 of file cart_controller.hpp.
getT_cur()
Affine3d CartController::getT_cur () inline
Definition at line 289 of file cart_controller.hpp.
References promp_trajectory_demo::T.
getT_init()
Affine3d CartController::getT_init () const inline
Definition at line 285 of file cart_controller.hpp.
getT_root()
Affine3d CartController::getT_root () inline
Definition at line 302 of file cart_controller.hpp.
getTft_eff()
Affine3d CartController::getTft_eff () inline
Definition at line 346 of file cart_controller.hpp.
getTrajectoryCmd() [1/2]
void CartController::getTrajectoryCmd (const VectorXd & q_des, const double & T, trajectory_msgs::JointTrajectory & cmd_trj) protected
Definition at line 490 of file cart_controller.cpp.
References nameJnt, nJnt, and promp_trajectory_demo::T.
Referenced by sendTrajectoryActionCmd(), and sendTrajectoryCmd().
getTrajectoryCmd() [2/2]
void CartController::getTrajectoryCmd (const VectorXd & q_des, const VectorXd & dq_des, const double & T, trajectory_msgs::JointTrajectory & cmd_trj) protected
Definition at line 503 of file cart_controller.cpp.
References nameJnt, nJnt, and promp_trajectory_demo::T.
getTransform_base()
Affine3d CartController::getTransform_base (std::string target)
Definition at line 249 of file cart_controller.cpp.
References chain_start, TransformUtility::getTransform(), robot_ns, and trans.
Referenced by init().
getVelocity()
void CartController::getVelocity (const KDL::Frame & frame, const KDL::Frame & prev_frame, const double & dt, KDL::Twist & twist) const
Definition at line 281 of file cart_controller.cpp.
References dt, rotation_util::getQuaternionError(), and promp_trajectory_demo::T.
init() [1/2]
void CartController::init (std::string robot) private
Definition at line 24 of file cart_controller.cpp.
Referenced by CartController().
init() [2/2]
void CartController::init (std::string robot, std::string hw_config) private
Definition at line 28 of file cart_controller.cpp.
References _q_cur, _q_init_expect, TransformUtility::canTransform(), cbArmMarker(), cbForce(), cbJntState(), chain, chain_end, chain_segs, chain_start, client, curStatePublisher, desStatePublisher, dt, eps, fk_solver_ptr, flagArmMarker, flagForce, flagJntState, freq, ftFound, getInitParam(), TransformUtility::getTransform(), getTransform_base(), hw_config_ns, initPose, initPoseFrame, jntCmdPublisher, jntFilter, jntStateSubscriber, kdl_solver_ptr, markerPublisher, myik_solver_ptr, nh, nJnt, posFilter, pubEefForce, publisher, publisherTopicName, resetService(), robot_ns, root_frame, service, spinner, subFlagPtrs, subForce, T_base_root, T_init, Tft_eff, th, tracik_solver_ptr, trans, urdf_param, useManipOpt, userArmMarker, velFilter, and vik_solver_ptr.
initDesWithJnt()
void CartController::initDesWithJnt (const KDL::JntArray & q_init) protected
Definition at line 375 of file cart_controller.cpp.
References _des_eef_pose, _des_eef_vel, fk_solver_ptr, mtx, and q_cur.
Referenced by cbJntState().
initWithJnt()
void CartController::initWithJnt (const KDL::JntArray & q_init) protected virtual
Definition at line 277 of file cart_controller.cpp.
Referenced by cbJntState().
isInitialized()
bool CartController::isInitialized () inline
Definition at line 327 of file cart_controller.hpp.
JntToCart() [1/2]
void CartController::JntToCart (const KDL::JntArray & q_in, const KDL::JntArray & dq_in, KDL::Frame & p_out, KDL::Twist & v_out) inline
Definition at line 268 of file cart_controller.hpp.
JntToCart() [2/2]
void CartController::JntToCart (const KDL::JntArray & q_in, KDL::Frame & p_out) inline
Definition at line 264 of file cart_controller.hpp.
JntVelToCartVel()
void CartController::JntVelToCartVel (const KDL::JntArray & q_in, const KDL::JntArray & dq_in, KDL::Twist & v_out) inline
Definition at line 272 of file cart_controller.hpp.
moveInitPos()
int CartController::moveInitPos (const KDL::JntArray & q_cur, const std::vector< std::string > nameJnt, std::vector< int > idxSegJnt) protected
Definition at line 381 of file cart_controller.cpp.
References _q_init_expect, CartController::s_moveInitPos::isFirst, kdl_solver_ptr, myik_solver_ptr, nameJnt, nJnt, publisher, q_cur, CartController::s_moveInitPos::q_des, CartController::s_moveInitPos::q_initial, q_rest, rc, sendPositionCmd(), sendTrajectoryActionCmd(), sendTrajectoryCmd(), sendVelocityCmd(), solver, promp_trajectory_demo::T, T_init, CartController::s_moveInitPos::t_s, and tracik_solver_ptr.
Referenced by cbJntState().
publishCurEffPoseVel()
void CartController::publishCurEffPoseVel (const KDL::Frame & cur_eef_pose, const KDL::Twist & cur_eef_vel)
Definition at line 611 of file cart_controller.cpp.
References _force, curStatePublisher, mtx, and publishState().
Referenced by getIKInput().
publishDesEffPoseVel()
void CartController::publishDesEffPoseVel (const KDL::Frame & des_eef_pose, const KDL::Twist & des_eef_vel)
Definition at line 607 of file cart_controller.cpp.
References des_eef_pose, des_eef_vel, desStatePublisher, and publishState().
Referenced by getIKInput().
publishMarker()
void CartController::publishMarker (const KDL::JntArray q_cur)
Definition at line 616 of file cart_controller.cpp.
References chain_start, markerPublisher, myik_solver_ptr, q_cur, and robot_ns.
publishState() [1/2]
void CartController::publishState (const KDL::Frame & pose, const KDL::Twist & vel, const geometry_msgs::Wrench & wrench, ros::Publisher * publisher)
Definition at line 590 of file cart_controller.cpp.
References getOperationEnable(), publisher, and tf2::toMsg().
publishState() [2/2]
void CartController::publishState (const KDL::Frame & pose, const KDL::Twist & vel, ros::Publisher * publisher)
Definition at line 586 of file cart_controller.cpp.
References publisher.
Referenced by publishCurEffPoseVel(), and publishDesEffPoseVel().
resetFt()
void CartController::resetFt ()
Definition at line 270 of file cart_controller.cpp.
References client.
Referenced by resetService(), and starting().
resetPose()
void CartController::resetPose ()
Definition at line 241 of file cart_controller.cpp.
References initialized, CartController::s_cbJntState::isFirst, and CartController::s_moveInitPos::isFirst.
Referenced by resetService().
resetService()
bool CartController::resetService (std_srvs::Empty::Request & req, std_srvs::Empty::Response & res) private
Definition at line 235 of file cart_controller.cpp.
References resetFt(), and resetPose().
Referenced by init().
sendPosCmd()
void CartController::sendPosCmd (const KDL::JntArray & q_des, const KDL::JntArray & dq_des, const double & dt)
Definition at line 816 of file cart_controller.cpp.
References dt, publisher, sendPositionCmd(), sendTrajectoryActionCmd(), sendTrajectoryCmd(), and sendVelocityCmd().
Referenced by update().
sendPositionCmd()
void CartController::sendPositionCmd (const VectorXd & q_des) protected
Definition at line 473 of file cart_controller.cpp.
References cmd, and jntCmdPublisher.
Referenced by moveInitPos(), sendPosCmd(), sendVelCmd(), and sendVelocityCmd().
sendTrajectoryActionCmd() [1/2]
void CartController::sendTrajectoryActionCmd (const VectorXd & q_des, const double & T) protected
Definition at line 527 of file cart_controller.cpp.
References getTrajectoryCmd(), jntCmdPublisher, and promp_trajectory_demo::T.
Referenced by moveInitPos(), sendPosCmd(), and sendVelCmd().
sendTrajectoryActionCmd() [2/2]
void CartController::sendTrajectoryActionCmd (const VectorXd & q_des, const VectorXd & dq_des, const double & T) protected
Definition at line 532 of file cart_controller.cpp.
References getTrajectoryCmd(), jntCmdPublisher, and promp_trajectory_demo::T.
sendTrajectoryCmd() [1/2]
void CartController::sendTrajectoryCmd (const VectorXd & q_des, const double & T) protected
Definition at line 515 of file cart_controller.cpp.
References getTrajectoryCmd(), jntCmdPublisher, and promp_trajectory_demo::T.
Referenced by moveInitPos(), sendPosCmd(), and sendVelCmd().
sendTrajectoryCmd() [2/2]
void CartController::sendTrajectoryCmd (const VectorXd & q_des, const VectorXd & dq_des, const double & T) protected
Definition at line 521 of file cart_controller.cpp.
References getTrajectoryCmd(), jntCmdPublisher, and promp_trajectory_demo::T.
sendVelCmd()
void CartController::sendVelCmd (const KDL::JntArray & q_des, const KDL::JntArray & dq_des, const double & dt)
Definition at line 836 of file cart_controller.cpp.
References dt, publisher, sendPositionCmd(), sendTrajectoryActionCmd(), sendTrajectoryCmd(), and sendVelocityCmd().
Referenced by update().
sendVelocityCmd() [1/2]
void CartController::sendVelocityCmd (const VectorXd & dq_des) protected
Definition at line 479 of file cart_controller.cpp.
References sendPositionCmd().
Referenced by moveInitPos(), sendPosCmd(), sendVelCmd(), and sendVelocityCmd().
sendVelocityCmd() [2/2]
void CartController::sendVelocityCmd (const VectorXd & q_des, const VectorXd & dq_des, const KDL::JntArray & q_cur, const bool & lastLoop) protected
Definition at line 483 of file cart_controller.cpp.
References cmd, q_cur, and sendVelocityCmd().
setDesired()
void CartController::setDesired (const KDL::Frame & des_eef_pose, const KDL::Twist & des_eef_vel) inline
Definition at line 331 of file cart_controller.hpp.
References mtx.
setqRest()
void CartController::setqRest (const KDL::JntArray & q_rest) inline
Definition at line 354 of file cart_controller.hpp.
signal_handler()
void CartController::signal_handler (int signum) static private
Definition at line 253 of file cart_controller.cpp.
References cmd, controller, nh, publisher, and robot_ns.
starting()
void CartController::starting (const ros::Time & time)
Starts controller.
Parameters
time Current time
Definition at line 630 of file cart_controller.cpp.
References gazebo_utility::checkGazeboInit(), subscriber_utility::checkSubTopic(), mtx, resetFt(), robot_ns, spinner, subFlagPtrs, and updateCurState().
Referenced by control().
startOperation()
void CartController::startOperation () inline
Definition at line 234 of file cart_controller.hpp.
stopping()
void CartController::stopping (const ros::Time & time)
Stops controller.
Parameters
time Current time
Definition at line 652 of file cart_controller.cpp.
References cmd, controller, jntCmdPublisher, and nJnt.
Referenced by control().
update() [1/2]
void CartController::update ()
Updates controller, i.e. computes the odometry and sets the new velocity commands.
Parameters
time Current time
period Time since the last called to update
Definition at line 732 of file cart_controller.cpp.
References freq.
Referenced by control(), and MultiCartController::control().
update() [2/2]
void CartController::update (const ros::Time & time, const ros::Duration & period)
Definition at line 735 of file cart_controller.cpp.
References _userManipU, controller, des_eef_pose, des_eef_vel, dt, filterJnt(), getIKInput(), kdl_solver_ptr, mtx, myik_solver_ptr, nJnt, prev_time, q_cur, rc, sendPosCmd(), sendVelCmd(), solver, promp_trajectory_demo::time, tracik_solver_ptr, updateCurState(), and userManipU.
updateCurState()
void CartController::updateCurState () inline
Definition at line 196 of file cart_controller.hpp.
Referenced by starting(), and update().
updateFilterCutoff()
void CartController::updateFilterCutoff (const double velFreq, const double jntFreq)
Definition at line 135 of file cart_controller.cpp.
References updateJntFilterCutoff(), and updateVelFilterCutoff().
updateJntFilterCutoff()
void CartController::updateJntFilterCutoff (const double jntFreq)
Definition at line 130 of file cart_controller.cpp.
References freq, jntFilter, and nJnt.
Referenced by updateFilterCutoff().
updatePosFilterCutoff()
void CartController::updatePosFilterCutoff (const double posFreq)
Definition at line 120 of file cart_controller.cpp.
References freq, and posFilter.
updateVelFilterCutoff()
void CartController::updateVelFilterCutoff (const double velFreq)
Definition at line 125 of file cart_controller.cpp.
References freq, and velFilter.
Referenced by updateFilterCutoff().
Member Data Documentation
_current_eef_pose
KDL::Frame CartController::_current_eef_pose protected
Definition at line 121 of file cart_controller.hpp.
_des_eef_pose
KDL::Frame CartController::_des_eef_pose protected
Definition at line 120 of file cart_controller.hpp.
Referenced by getDesState(), and initDesWithJnt().
_des_eef_vel
KDL::Twist CartController::_des_eef_vel protected
Definition at line 122 of file cart_controller.hpp.
Referenced by getDesState(), and initDesWithJnt().
_disable
bool CartController::_disable = true protected
Definition at line 127 of file cart_controller.hpp.
Referenced by getDesState().
_dq_cur
KDL::JntArray CartController::_dq_cur protected
Definition at line 129 of file cart_controller.hpp.
Referenced by cbJntState().
_dq_cur_t
KDL::JntArray CartController::_dq_cur_t protected
Definition at line 129 of file cart_controller.hpp.
_force
geometry_msgs::WrenchStamped CartController::_force protected
Definition at line 124 of file cart_controller.hpp.
Referenced by cbForce(), and publishCurEffPoseVel().
_passThrough
bool CartController::_passThrough = false protected
Definition at line 127 of file cart_controller.hpp.
Referenced by getDesState().
_q_cur
KDL::JntArray CartController::_q_cur protected
Definition at line 129 of file cart_controller.hpp.
Referenced by cbJntState(), and init().
_q_cur_t
KDL::JntArray CartController::_q_cur_t protected
Definition at line 129 of file cart_controller.hpp.
_q_init_expect
std::vector<double> CartController::_q_init_expect private
Definition at line 70 of file cart_controller.hpp.
Referenced by init(), and moveInitPos().
_userManipU
Matrix3d CartController::_userManipU = Matrix3d::Identity() protected
Definition at line 104 of file cart_controller.hpp.
Referenced by cbArmMarker(), and update().
br
tf2_ros::TransformBroadcaster CartController::br protected
Definition at line 134 of file cart_controller.hpp.
chain
KDL::Chain CartController::chain protected
Definition at line 143 of file cart_controller.hpp.
Referenced by init().
chain_end
std::string CartController::chain_end protected
Definition at line 150 of file cart_controller.hpp.
Referenced by cbForce(), getInitParam(), and init().
chain_segs
std::vector<KDL::Segment> CartController::chain_segs protected
Definition at line 144 of file cart_controller.hpp.
Referenced by cbJntState(), and init().
chain_start
std::string CartController::chain_start protected
Definition at line 150 of file cart_controller.hpp.
Referenced by getInitParam(), getTransform_base(), init(), and publishMarker().
client
ros::ServiceClient CartController::client private
Definition at line 55 of file cart_controller.hpp.
Referenced by init(), and resetFt().
cmd
std_msgs::Float64MultiArray CartController::cmd private
Definition at line 52 of file cart_controller.hpp.
Referenced by sendPositionCmd(), sendVelocityCmd(), signal_handler(), and stopping().
controller
ControllerType CartController::controller protected
Definition at line 93 of file cart_controller.hpp.
Referenced by getInitParam(), signal_handler(), stopping(), and update().
current_eef_pose
KDL::Frame CartController::current_eef_pose private
Definition at line 49 of file cart_controller.hpp.
curStatePublisher
ros::Publisher CartController::curStatePublisher
Definition at line 367 of file cart_controller.hpp.
Referenced by init(), and publishCurEffPoseVel().
des_eef_pose
KDL::Frame CartController::des_eef_pose private
Definition at line 49 of file cart_controller.hpp.
Referenced by getIKInput(), publishDesEffPoseVel(), and update().
des_eef_vel
KDL::Twist CartController::des_eef_vel private
Definition at line 50 of file cart_controller.hpp.
Referenced by filterDesEffPoseVel(), getIKInput(), publishDesEffPoseVel(), and update().
desStatePublisher
ros::Publisher CartController::desStatePublisher
Definition at line 367 of file cart_controller.hpp.
Referenced by init(), and publishDesEffPoseVel().
dq_cur
KDL::JntArray CartController::dq_cur private
Definition at line 51 of file cart_controller.hpp.
Referenced by cbJntState(), and getIKInput().
dt
double CartController::dt
Definition at line 362 of file cart_controller.hpp.
Referenced by getVelocity(), init(), sendPosCmd(), sendVelCmd(), and update().
eps
const double CartController::eps = 1e-6
Definition at line 365 of file cart_controller.hpp.
Referenced by init().
fk_solver_ptr
std::unique_ptr<KDL::ChainFkSolverPos_recursive> CartController::fk_solver_ptr protected
Definition at line 142 of file cart_controller.hpp.
Referenced by init(), and initDesWithJnt().
flagArmMarker
bool CartController::flagArmMarker = false protected
Definition at line 105 of file cart_controller.hpp.
Referenced by cbArmMarker(), and init().
flagEffPose
bool CartController::flagEffPose = false protected
Definition at line 102 of file cart_controller.hpp.
flagForce
bool CartController::flagForce = false protected
Definition at line 125 of file cart_controller.hpp.
Referenced by cbForce(), and init().
flagJntState
bool CartController::flagJntState = false
Definition at line 369 of file cart_controller.hpp.
Referenced by cbJntState(), and init().
freq
double CartController::freq = 500.0
Definition at line 363 of file cart_controller.hpp.
Referenced by control(), getInitParam(), init(), update(), updateJntFilterCutoff(), updatePosFilterCutoff(), and updateVelFilterCutoff().
ftFound
bool CartController::ftFound = false private
Definition at line 89 of file cart_controller.hpp.
Referenced by init().
hw_config_ns
std::string CartController::hw_config_ns = "" protected
Definition at line 150 of file cart_controller.hpp.
Referenced by getInitParam(), and init().
index
const int CartController::index = 0 protected
Definition at line 164 of file cart_controller.hpp.
initialized
bool CartController::initialized = false private
Definition at line 81 of file cart_controller.hpp.
Referenced by cbJntState(), and resetPose().
initPose
std::vector<double> CartController::initPose private
Definition at line 73 of file cart_controller.hpp.
Referenced by getInitParam(), and init().
initPoseFrame
std::string CartController::initPoseFrame private
Definition at line 72 of file cart_controller.hpp.
Referenced by getInitParam(), and init().
jntCmdPublisher
ros::Publisher CartController::jntCmdPublisher
Definition at line 367 of file cart_controller.hpp.
Referenced by init(), sendPositionCmd(), sendTrajectoryActionCmd(), sendTrajectoryCmd(), and stopping().
jntFilter
std::vector<butterworth> CartController::jntFilter protected
Definition at line 131 of file cart_controller.hpp.
Referenced by filterJnt(), init(), and updateJntFilterCutoff().
jntStateSubscriber
ros::Subscriber CartController::jntStateSubscriber protected
Definition at line 97 of file cart_controller.hpp.
Referenced by init().
kdl_solver_ptr
std::unique_ptr<KDL::ChainIkSolverPos_NR_JL> CartController::kdl_solver_ptr protected
Definition at line 138 of file cart_controller.hpp.
Referenced by init(), moveInitPos(), and update().
m
const unsigned int CartController::m = 6 protected
Definition at line 116 of file cart_controller.hpp.
markerPublisher
ros::Publisher CartController::markerPublisher
Definition at line 367 of file cart_controller.hpp.
Referenced by init(), and publishMarker().
mtx
std::mutex CartController::mtx
Definition at line 368 of file cart_controller.hpp.
Referenced by cbArmMarker(), cbForce(), getDesState(), initDesWithJnt(), publishCurEffPoseVel(), starting(), and update().
mtx_q
std::mutex CartController::mtx_q private
Definition at line 47 of file cart_controller.hpp.
Referenced by cbJntState().
myik_solver_ptr
std::shared_ptr<MyIK::MyIK> CartController::myik_solver_ptr protected
Definition at line 147 of file cart_controller.hpp.
Referenced by init(), moveInitPos(), publishMarker(), and update().
nameJnt
std::vector<std::string> CartController::nameJnt protected
Definition at line 118 of file cart_controller.hpp.
Referenced by cbJntState(), getTrajectoryCmd(), and moveInitPos().
nh
ros::NodeHandle CartController::nh protected
Definition at line 95 of file cart_controller.hpp.
Referenced by CartController(), getInitParam(), init(), and signal_handler().
nh_
ros::NodeHandle CartController::nh_ private
Definition at line 44 of file cart_controller.hpp.
nJnt
unsigned int CartController::nJnt protected
Definition at line 115 of file cart_controller.hpp.
Referenced by cbJntState(), filterJnt(), getTrajectoryCmd(), init(), moveInitPos(), stopping(), update(), and updateJntFilterCutoff().
num_samples
int CartController::num_samples protected
Definition at line 108 of file cart_controller.hpp.
posFilter
std::vector<butterworth> CartController::posFilter protected
Definition at line 131 of file cart_controller.hpp.
Referenced by init(), and updatePosFilterCutoff().
prev_time
ros::Time CartController::prev_time = ros::Time::now() private
Definition at line 87 of file cart_controller.hpp.
Referenced by update().
pubEefForce
ros::Publisher CartController::pubEefForce private
Definition at line 45 of file cart_controller.hpp.
Referenced by cbForce(), and init().
publisher
PublisherType CartController::publisher protected
Definition at line 94 of file cart_controller.hpp.
Referenced by getInitParam(), init(), moveInitPos(), publishState(), sendPosCmd(), sendVelCmd(), and signal_handler().
publisherTopicName
std::string CartController::publisherTopicName private
Definition at line 76 of file cart_controller.hpp.
Referenced by getInitParam(), and init().
q_cur
KDL::JntArray CartController::q_cur private
Definition at line 51 of file cart_controller.hpp.
Referenced by cbJntState(), getIKInput(), initDesWithJnt(), moveInitPos(), publishMarker(), sendVelocityCmd(), and update().
q_rest
KDL::JntArray CartController::q_rest private
Definition at line 83 of file cart_controller.hpp.
Referenced by moveInitPos().
queue
ros::CallbackQueue CartController::queue private
Definition at line 42 of file cart_controller.hpp.
rc
int CartController::rc private
Definition at line 54 of file cart_controller.hpp.
Referenced by moveInitPos(), and update().
robot_ns
std::string CartController::robot_ns = "" protected
Definition at line 150 of file cart_controller.hpp.
Referenced by cbForce(), getTransform_base(), init(), publishMarker(), signal_handler(), and starting().
root_frame
std::string CartController::root_frame protected
Definition at line 149 of file cart_controller.hpp.
Referenced by CartController(), getInitParam(), and init().
s_cbJntState
struct CartController::s_cbJntState CartController::s_cbJntState private
s_moveInitPos
struct CartController::s_moveInitPos CartController::s_moveInitPos private
service
ros::ServiceServer CartController::service private
Definition at line 78 of file cart_controller.hpp.
Referenced by init().
solver
SolverType CartController::solver protected
Definition at line 92 of file cart_controller.hpp.
Referenced by getInitParam(), moveInitPos(), and update().
spinner
boost::shared_ptr<ros::AsyncSpinner> CartController::spinner private
Definition at line 43 of file cart_controller.hpp.
Referenced by init(), and starting().
spinner_
boost::shared_ptr<ros::AsyncSpinner> CartController::spinner_ private
Definition at line 43 of file cart_controller.hpp.
subFlagPtrs
std::vector<bool*> CartController::subFlagPtrs protected
Definition at line 100 of file cart_controller.hpp.
Referenced by init(), and starting().
subForce
ros::Subscriber CartController::subForce protected
Definition at line 97 of file cart_controller.hpp.
Referenced by init().
T_base_root
Affine3d CartController::T_base_root protected
Definition at line 151 of file cart_controller.hpp.
Referenced by init().
T_init
Affine3d CartController::T_init protected
Definition at line 112 of file cart_controller.hpp.
Referenced by init(), and moveInitPos().
Tft_eff
Affine3d CartController::Tft_eff protected
Definition at line 113 of file cart_controller.hpp.
Referenced by cbForce(), and init().
th
ros::TransportHints CartController::th = ros::TransportHints().tcpNoDelay(true) protected
Definition at line 98 of file cart_controller.hpp.
Referenced by init().
timeout
double CartController::timeout protected
Definition at line 110 of file cart_controller.hpp.
tracik_solver_ptr
std::unique_ptr<TRAC_IK::TRAC_IK> CartController::tracik_solver_ptr protected
Definition at line 141 of file cart_controller.hpp.
Referenced by init(), moveInitPos(), and update().
trans
TransformUtility CartController::trans protected
Definition at line 133 of file cart_controller.hpp.
Referenced by getTransform_base(), and init().
urdf_param
std::string CartController::urdf_param protected
Definition at line 150 of file cart_controller.hpp.
Referenced by init().
useManipOpt
bool CartController::useManipOpt = false protected
Definition at line 106 of file cart_controller.hpp.
Referenced by getInitParam(), and init().
userArmMarker
ros::Subscriber CartController::userArmMarker protected
Definition at line 97 of file cart_controller.hpp.
Referenced by init().
userManipU
Matrix3d CartController::userManipU private
Definition at line 53 of file cart_controller.hpp.
Referenced by update().
velFilter
std::vector<butterworth> CartController::velFilter protected
Definition at line 131 of file cart_controller.hpp.
Referenced by filterDesEffPoseVel(), init(), and updateVelFilterCutoff().
vik_solver_ptr
std::unique_ptr<KDL::ChainIkSolverVel_pinv> CartController::vik_solver_ptr protected
Definition at line 137 of file cart_controller.hpp.
Referenced by init().
The documentation for this class was generated from the following files:
cart_controller.hpp
cart_controller.cpp