OpenHRC: geometry_msgs_utility::Point Class Reference
geometry_msgs_utility::Point Class Reference
#include <Point.h>
Public Member Functions
Point (int order, double cutoff_freq, double sampling_freq)
Point ()
~Point ()
void LPF (geometry_msgs::Point raw_point, geometry_msgs::Point &filtered_point)
void diff (geometry_msgs::Point point, geometry_msgs::Point &diff_point)
void diff_LPF (geometry_msgs::Point point, geometry_msgs::Point &filtered_point)
void initLPF (int order, double cutoff_freq, double sampling_freq)
Private Attributes
double delta_t
std::vector< std::shared_ptr< butterworth > > _filter
Detailed Description
Definition at line 29 of file Point.h.
Constructor & Destructor Documentation
Point() [1/2]
geometry_msgs_utility::Point::Point (int order, double cutoff_freq, double sampling_freq)
Definition at line 11 of file Point.cpp.
References initLPF().
Point() [2/2]
geometry_msgs_utility::Point::Point () inline
Definition at line 36 of file Point.h.
~Point()
geometry_msgs_utility::Point::~Point ()
Definition at line 15 of file Point.cpp.
Member Function Documentation
diff()
void geometry_msgs_utility::Point::diff (geometry_msgs::Point point, geometry_msgs::Point & diff_point)
Definition at line 34 of file Point.cpp.
References delta_t, and promp_trajectory_publisher::point.
Referenced by diff_LPF().
diff_LPF()
void geometry_msgs_utility::Point::diff_LPF (geometry_msgs::Point point, geometry_msgs::Point & filtered_point)
Definition at line 42 of file Point.cpp.
References diff(), LPF(), and promp_trajectory_publisher::point.
initLPF()
void geometry_msgs_utility::Point::initLPF (int order, double cutoff_freq, double sampling_freq)
Definition at line 21 of file Point.cpp.
References _filter, and delta_t.
Referenced by Point().
LPF()
void geometry_msgs_utility::Point::LPF (geometry_msgs::Point raw_point, geometry_msgs::Point & filtered_point)
Definition at line 28 of file Point.cpp.
References _filter.
Referenced by diff_LPF().
Member Data Documentation
_filter
std::vector<std::shared_ptr<butterworth> > geometry_msgs_utility::Point::_filter private
Definition at line 32 of file Point.h.
Referenced by initLPF(), and LPF().
delta_t
double geometry_msgs_utility::Point::delta_t private
Definition at line 31 of file Point.h.
Referenced by diff(), and initLPF().
The documentation for this class was generated from the following files:
Point.h
Point.cpp