OpenHRC: math_utility Namespace Reference
math_utility Namespace Reference
Classes
class Integrator
Functions
double sigmoid (double x, double gain)
double sigmoid (double x)
bool inConvex (Eigen::Vector2d p, std::vector< Eigen::Vector2d > apexes)
template<class T >
T clamp (T value, T min, T max)
template<class T >
T deadZone (T value, T upper, T lower)
template<class T >
T deadZone (T value, T upper)
template<typename T >
Eigen::Matrix< T, 3, 3 > skew (const Eigen::Matrix< T, 3, 1 > &vec)
Eigen::VectorXd concatenateVecOfVec (std::vector< Eigen::VectorXd > vecOfVec)
std::vector< Eigen::VectorXd > splitVec (Eigen::VectorXd vec, std::vector< int > num)
std::vector< Eigen::VectorXd > splitVec (Eigen::VectorXd vec, std::vector< Eigen::VectorXd > &vecOfVec)
template<typename T >
T sgn (T val)
Eigen::Quaterniond QuatFromTwoVectors (Eigen::Vector3d u, Eigen::Vector3d v)
Function Documentation
clamp()
template<class T > T math_utility::clamp (T value, T min, T max)
Definition at line 49 of file math_utility.h.
Referenced by geometry_msgs_utility::clamp().
concatenateVecOfVec()
Eigen::VectorXd math_utility::concatenateVecOfVec (std::vector< Eigen::VectorXd > vecOfVec) inline
Definition at line 75 of file math_utility.h.
deadZone() [1/2]
template<class T > T math_utility::deadZone (T value, T upper)
Definition at line 64 of file math_utility.h.
References deadZone().
deadZone() [2/2]
template<class T > T math_utility::deadZone (T value, T upper, T lower)
Definition at line 55 of file math_utility.h.
Referenced by geometry_msgs_utility::deadZone(), and deadZone().
inConvex()
bool math_utility::inConvex (Eigen::Vector2d p, std::vector< Eigen::Vector2d > apexes) inline
Definition at line 25 of file math_utility.h.
References count.
QuatFromTwoVectors()
Eigen::Quaterniond math_utility::QuatFromTwoVectors (Eigen::Vector3d u, Eigen::Vector3d v) inline
Definition at line 118 of file math_utility.h.
sgn()
template<typename T > T math_utility::sgn (T val)
Definition at line 113 of file math_utility.h.
References promp_trajectory_demo::T.
Referenced by TEST().
sigmoid() [1/2]
double math_utility::sigmoid (double x) inline
Definition at line 17 of file math_utility.h.
References sigmoid(), promp_trajectory_publisher::x, and promp_trajectory_publisher::y.
sigmoid() [2/2]
double math_utility::sigmoid (double x, double gain) inline
Definition at line 11 of file math_utility.h.
References promp_trajectory_publisher::x, and promp_trajectory_publisher::y.
Referenced by sigmoid().
skew()
template<typename T > Eigen::Matrix<T, 3, 3> math_utility::skew (const Eigen::Matrix< T, 3, 1 > & vec)
Definition at line 70 of file math_utility.h.
References promp_trajectory_demo::T.
splitVec() [1/2]
std::vector<Eigen::VectorXd> math_utility::splitVec (Eigen::VectorXd vec, std::vector< Eigen::VectorXd > & vecOfVec) inline
Definition at line 102 of file math_utility.h.
References splitVec().
splitVec() [2/2]
std::vector<Eigen::VectorXd> math_utility::splitVec (Eigen::VectorXd vec, std::vector< int > num) inline
Definition at line 91 of file math_utility.h.
Referenced by splitVec().