OpenHRC: geometry_msgs_utility Namespace Reference
geometry_msgs_utility Namespace Reference
Classes
class Point
class Vector3
struct paramDeadZone
class Wrench
class WrenchStamped
Functions
double dist (geometry_msgs::Point point1, geometry_msgs::Point point2)
void initPoint (geometry_msgs::Point &point, double x, double y, double z)
void initPoint (geometry_msgs::Point &point, double val)
void clamp (geometry_msgs::Point &point, double x_max, double y_max, double z_max, double x_min, double y_min, double z_min)
void clamp (geometry_msgs::Point &point, double max, double min)
void clamp_moreThan (geometry_msgs::Point &point, double x, double y, double z)
void clamp_moreThan (geometry_msgs::Point &point, double val)
void clamp_lessThan (geometry_msgs::Point &point, double x, double y, double z)
void clamp_lessThan (geometry_msgs::Point &point, double val)
geometry_msgs::Point error (geometry_msgs::Point point1, geometry_msgs::Point point2)
geometry_msgs::Point sum (std::vector< geometry_msgs::Point > points)
geometry_msgs::Point average (std::vector< geometry_msgs::Point > points)
geometry_msgs::Twist checkNanInf (geometry_msgs::Twist cmd)
geometry_msgs::Twist cropMinMax (geometry_msgs::Twist cmd, geometry_msgs::Twist min, geometry_msgs::Twist max)
Eigen::VectorXd toVector (geometry_msgs::Twist twist, Eigen::VectorXd &vector)
Eigen::VectorXd toVector (geometry_msgs::Twist twist)
geometry_msgs::Twist fromVector (Eigen::VectorXd vector, geometry_msgs::Twist &twist)
void deadZone (geometry_msgs::Wrench raw_wrench, geometry_msgs::Wrench &filtered_wrench, paramDeadZone param)
geometry_msgs::Wrench transformFT (geometry_msgs::Wrench ft_in, const Affine3d trans)
void deadZone (geometry_msgs::WrenchStamped wrenchStamped, geometry_msgs::WrenchStamped &filtered_wrenchStamped, paramDeadZone param)
Function Documentation
average()
geometry_msgs::Point geometry_msgs_utility::average (std::vector< geometry_msgs::Point > points)
Definition at line 120 of file Point.cpp.
References sum().
checkNanInf()
geometry_msgs::Twist geometry_msgs_utility::checkNanInf (geometry_msgs::Twist cmd)
Definition at line 11 of file Twist.cpp.
References error().
clamp() [1/2]
void geometry_msgs_utility::clamp (geometry_msgs::Point & point, double max, double min)
Definition at line 67 of file Point.cpp.
References clamp(), and promp_trajectory_publisher::point.
clamp() [2/2]
void geometry_msgs_utility::clamp (geometry_msgs::Point & point, double x_max, double y_max, double z_max, double x_min, double y_min, double z_min)
Definition at line 61 of file Point.cpp.
References math_utility::clamp(), and promp_trajectory_publisher::point.
Referenced by clamp().
clamp_lessThan() [1/2]
void geometry_msgs_utility::clamp_lessThan (geometry_msgs::Point & point, double val)
Definition at line 97 of file Point.cpp.
References clamp_lessThan(), and promp_trajectory_publisher::point.
clamp_lessThan() [2/2]
void geometry_msgs_utility::clamp_lessThan (geometry_msgs::Point & point, double x, double y, double z)
Definition at line 86 of file Point.cpp.
References promp_trajectory_publisher::point, promp_trajectory_publisher::x, promp_trajectory_publisher::y, and promp_trajectory_publisher::z.
Referenced by clamp_lessThan().
clamp_moreThan() [1/2]
void geometry_msgs_utility::clamp_moreThan (geometry_msgs::Point & point, double val)
Definition at line 82 of file Point.cpp.
References clamp_moreThan(), and promp_trajectory_publisher::point.
clamp_moreThan() [2/2]
void geometry_msgs_utility::clamp_moreThan (geometry_msgs::Point & point, double x, double y, double z)
Definition at line 71 of file Point.cpp.
References promp_trajectory_publisher::point, promp_trajectory_publisher::x, promp_trajectory_publisher::y, and promp_trajectory_publisher::z.
Referenced by clamp_moreThan().
cropMinMax()
geometry_msgs::Twist geometry_msgs_utility::cropMinMax (geometry_msgs::Twist cmd, geometry_msgs::Twist min, geometry_msgs::Twist max)
Definition at line 33 of file Twist.cpp.
References tf2::fromMsg(), and tf2::toMsg().
deadZone() [1/2]
void geometry_msgs_utility::deadZone (geometry_msgs::Wrench raw_wrench, geometry_msgs::Wrench & filtered_wrench, paramDeadZone param)
Definition at line 59 of file Wrench.cpp.
References math_utility::deadZone(), geometry_msgs_utility::paramDeadZone::force_lower, geometry_msgs_utility::paramDeadZone::force_upper, geometry_msgs_utility::paramDeadZone::torque_lower, and geometry_msgs_utility::paramDeadZone::torque_upper.
Referenced by deadZone(), and geometry_msgs_utility::Wrench::deadZone_LPF().
deadZone() [2/2]
void geometry_msgs_utility::deadZone (geometry_msgs::WrenchStamped wrenchStamped, geometry_msgs::WrenchStamped & filtered_wrenchStamped, paramDeadZone param)
Definition at line 12 of file WrenchStamped.cpp.
References deadZone().
dist()
double geometry_msgs_utility::dist (geometry_msgs::Point point1, geometry_msgs::Point point2)
Definition at line 48 of file Point.cpp.
Referenced by MyIK::MyIK::getRandomJnt(), and MyIK::MyIK::getRandomJntVel().
error()
geometry_msgs::Point geometry_msgs_utility::error (geometry_msgs::Point point1, geometry_msgs::Point point2)
Definition at line 101 of file Point.cpp.
Referenced by checkNanInf().
fromVector()
geometry_msgs::Twist geometry_msgs_utility::fromVector (Eigen::VectorXd vector, geometry_msgs::Twist & twist) inline
Definition at line 49 of file Twist.h.
initPoint() [1/2]
void geometry_msgs_utility::initPoint (geometry_msgs::Point & point, double val)
Definition at line 57 of file Point.cpp.
References initPoint(), and promp_trajectory_publisher::point.
initPoint() [2/2]
void geometry_msgs_utility::initPoint (geometry_msgs::Point & point, double x, double y, double z)
Definition at line 52 of file Point.cpp.
References promp_trajectory_publisher::point, promp_trajectory_publisher::x, promp_trajectory_publisher::y, and promp_trajectory_publisher::z.
Referenced by initPoint().
sum()
geometry_msgs::Point geometry_msgs_utility::sum (std::vector< geometry_msgs::Point > points)
Definition at line 110 of file Point.cpp.
Referenced by average(), BayesNormalGamma::estimate(), promp_trajectory_service::load_data(), and std_utility::weightedSum().
toVector() [1/2]
Eigen::VectorXd geometry_msgs_utility::toVector (geometry_msgs::Twist twist) inline
Definition at line 44 of file Twist.h.
toVector() [2/2]
Eigen::VectorXd geometry_msgs_utility::toVector (geometry_msgs::Twist twist, Eigen::VectorXd & vector) inline
Definition at line 33 of file Twist.h.
transformFT()
geometry_msgs::Wrench geometry_msgs_utility::transformFT (geometry_msgs::Wrench ft_in, const Affine3d trans) inline
Definition at line 53 of file Wrench.h.
References tf2::fromMsg(), tf2::toMsg(), and TransformUtility::transformFT().
Referenced by CartController::cbForce().