OpenHRC: subscriber_utility Namespace Reference
subscriber_utility Namespace Reference
Functions
bool checkTopic (std::vector< bool * > VecSubFlagPtr, std::mutex *mtx, std::string name)
bool checkSubTopic (std::vector< bool * > VecSubFlagPtr, std::mutex *mtx)
bool checkSubTopic (std::vector< bool * > VecSubFlagPtr, std::mutex *mtx, std::string robot_ns)
bool checkSubTopic (std::vector< bool * > VecSubFlagPtr, std::mutex *mtx, std::string name, std::string robot_ns)
Function Documentation
checkSubTopic() [1/3]
bool subscriber_utility::checkSubTopic (std::vector< bool * > VecSubFlagPtr, std::mutex * mtx) inline
Definition at line 36 of file subscriber_utility.h.
References checkTopic(), and mtx.
Referenced by ForwardingController::control(), and CartController::starting().
checkSubTopic() [2/3]
bool subscriber_utility::checkSubTopic (std::vector< bool * > VecSubFlagPtr, std::mutex * mtx, std::string name, std::string robot_ns) inline
Definition at line 44 of file subscriber_utility.h.
References checkTopic(), and mtx.
checkSubTopic() [3/3]
bool subscriber_utility::checkSubTopic (std::vector< bool * > VecSubFlagPtr, std::mutex * mtx, std::string robot_ns) inline
Definition at line 40 of file subscriber_utility.h.
References checkTopic(), and mtx.
checkTopic()
bool subscriber_utility::checkTopic (std::vector< bool * > VecSubFlagPtr, std::mutex * mtx, std::string name) inline
Definition at line 10 of file subscriber_utility.h.
References mtx.
Referenced by checkSubTopic().