OpenHRC: model_utility Namespace Reference
model_utility Namespace Reference
Functions
urdf::Model getURDFModel (const std::string URDF_param, ros::NodeHandle nh)
KDL::Chain getKDLChain (const urdf::Model &robot_model, const std::string &base_link, const std::string &tip_link)
void getBounds (const urdf::Model &robot_model, const KDL::Chain &chain, const double mergin, KDL::JntArray &lb, KDL::JntArray &ub, KDL::JntArray &vb)
Function Documentation
getBounds()
void model_utility::getBounds (const urdf::Model & robot_model, const KDL::Chain & chain, const double mergin, KDL::JntArray & lb, KDL::JntArray & ub, KDL::JntArray & vb) inline
Definition at line 41 of file model_utility.h.
Referenced by MyIK::MyIK::MyIK().
getKDLChain()
KDL::Chain model_utility::getKDLChain (const urdf::Model & robot_model, const std::string & base_link, const std::string & tip_link) inline
Definition at line 27 of file model_utility.h.
Referenced by MyIK::MyIK::MyIK().
getURDFModel()
urdf::Model model_utility::getURDFModel (const std::string URDF_param, ros::NodeHandle nh) inline
Definition at line 9 of file model_utility.h.
Referenced by MyIK::MyIK::MyIK().