OpenHRC: promp_trajectory_demo Namespace Reference
promp_trajectory_demo Namespace Reference
Variables
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(SCRIPT_DIR, "trajectory")
n_case
list trajs
list promps = []
int n_demos = 100
list T = [np.array(trajs[mode][i]["t"].values) for i in range(100)]
px = np.array([trajs[mode][i]["px"].values for i in range(100)])
list py = [trajs[mode][i]["py"].values for i in range(100)]
list pz = [trajs[mode][i]["pz"].values for i in range(100)]
list Y
list dy = trajs[mode][0]["vx"]
list ddy = trajs[mode][0]["ax"]
y_conditional_cov = np.array([0.0000025, 0.0000025, 0.0000025])
promp = ProMP(n_dims=3, n_weights_per_dim=10)
list y_cond = [0.1, 0.2, 0.3]
list Y_cmeans = []
list dY_cmeans = []
float t_max = 5.0
time = np.arange(0.0, t_max, 0.01)
cpromp
Y_cmean = cpromp.mean_trajectory(time)
dY_cmean = cpromp.mean_velocities(time)
list test = [2, 4, 3]
ax = plt.subplot(311)
label
bbox_inches
loc
ncol
Detailed Description
=================
Conditional ProMP
=================
Probabilistic Movement Primitives (ProMPs) define distributions over
trajectories that can be conditioned on viapoints. In this example, we
plot the resulting posterior distribution after conditioning on varying
start positions.
Variable Documentation
ax
promp_trajectory_demo.ax = plt.subplot(311)
Definition at line 78 of file promp_trajectory_demo.py.
bbox_inches
promp_trajectory_demo.bbox_inches
Definition at line 100 of file promp_trajectory_demo.py.
cpromp
promp_trajectory_demo.cpromp
Initial value:
 =  promp.condition_position(
         np.array(y_cond), y_cov=y_conditional_cov, t=0.0, t_max=t_max)
Definition at line 61 of file promp_trajectory_demo.py.
DATA_DIR
promp_trajectory_demo.DATA_DIR = os.path.join(SCRIPT_DIR, "trajectory")
Definition at line 23 of file promp_trajectory_demo.py.
ddy
list promp_trajectory_demo.ddy = trajs[mode][0]["ax"]
Definition at line 45 of file promp_trajectory_demo.py.
dy
list promp_trajectory_demo.dy = trajs[mode][0]["vx"]
Definition at line 44 of file promp_trajectory_demo.py.
dY_cmean
promp_trajectory_demo.dY_cmean = cpromp.mean_velocities(time)
Definition at line 65 of file promp_trajectory_demo.py.
dY_cmeans
list promp_trajectory_demo.dY_cmeans = []
Definition at line 56 of file promp_trajectory_demo.py.
label
promp_trajectory_demo.label
Definition at line 80 of file promp_trajectory_demo.py.
loc
promp_trajectory_demo.loc
Definition at line 112 of file promp_trajectory_demo.py.
n_case
promp_trajectory_demo.n_case
Initial value:
 =  sum(os.path.isdir(os.path.join(DATA_DIR, name))
              for name in os.listdir(DATA_DIR))
Definition at line 24 of file promp_trajectory_demo.py.
n_demos
int promp_trajectory_demo.n_demos = 100
Definition at line 35 of file promp_trajectory_demo.py.
ncol
promp_trajectory_demo.ncol
Definition at line 112 of file promp_trajectory_demo.py.
promp
promp_trajectory_demo.promp = ProMP(n_dims=3, n_weights_per_dim=10)
Definition at line 49 of file promp_trajectory_demo.py.
promps
list promp_trajectory_demo.promps = []
Definition at line 32 of file promp_trajectory_demo.py.
px
promp_trajectory_demo.px = np.array([trajs[mode][i]["px"].values for i in range(100)])
Definition at line 37 of file promp_trajectory_demo.py.
py
list promp_trajectory_demo.py = [trajs[mode][i]["py"].values for i in range(100)]
Definition at line 38 of file promp_trajectory_demo.py.
pz
list promp_trajectory_demo.pz = [trajs[mode][i]["pz"].values for i in range(100)]
Definition at line 39 of file promp_trajectory_demo.py.
SCRIPT_DIR
promp_trajectory_demo.SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
Definition at line 22 of file promp_trajectory_demo.py.
T
list promp_trajectory_demo.T = [np.array(trajs[mode][i]["t"].values) for i in range(100)]
Definition at line 36 of file promp_trajectory_demo.py.
Referenced by MyIK::MyIK.CartToJnt(), MyIK::MyIK.CartToJntVel_pinv(), MyIK::MyIK.CartToJntVel_qp_manipOpt(), ArmPerception.cbBodyMarker(), butterworth.get_coefficients(), MyIK.getCartError(), CartController.getDesState(), MultiCartController.getEnumParam(), MyIK::MyIK.getManipulabilityMarker(), CartController.getT_cur(), CartController.getTrajectoryCmd(), CartController.getVelocity(), ForwardingController.moveInitJntPos(), CartController.moveInitPos(), CartController.sendTrajectoryActionCmd(), CartController.sendTrajectoryCmd(), math_utility.sgn(), and math_utility.skew().
t_max
float promp_trajectory_demo.t_max = 5.0
Definition at line 58 of file promp_trajectory_demo.py.
test
list promp_trajectory_demo.test = [2, 4, 3]
Definition at line 76 of file promp_trajectory_demo.py.
time
promp_trajectory_demo.time = np.arange(0.0, t_max, 0.01)
Definition at line 59 of file promp_trajectory_demo.py.
Referenced by TransformUtility.canTransform(), std_utility.getDatetimeStr(), TransformUtility.getTransform(), MultiCartController.publishState(), CartController.update(), and MultiCartController.update().
trajs
list promp_trajectory_demo.trajs
Initial value:
 =  [[pd.read_csv(DATA_DIR+"/case_" +
                       str(k)+"/"+str(i+1) + ".csv") for i in range(100)] for k in range(n_case)]
Definition at line 28 of file promp_trajectory_demo.py.
Y
list promp_trajectory_demo.Y
Initial value:
 =  [np.array([[px[i][j], py[i][j], pz[i][j]]
                    for j in range(px[i].size)]) for i in range(n_demos)]
Definition at line 41 of file promp_trajectory_demo.py.
Y_cmean
promp_trajectory_demo.Y_cmean = cpromp.mean_trajectory(time)
Definition at line 64 of file promp_trajectory_demo.py.
Y_cmeans
list promp_trajectory_demo.Y_cmeans = []
Definition at line 55 of file promp_trajectory_demo.py.
y_cond
list promp_trajectory_demo.y_cond = [0.1, 0.2, 0.3]
Definition at line 54 of file promp_trajectory_demo.py.
y_conditional_cov
promp_trajectory_demo.y_conditional_cov = np.array([0.0000025, 0.0000025, 0.0000025])
Definition at line 48 of file promp_trajectory_demo.py.