OpenHRC: dummy_trajectory_generation Namespace Reference
dummy_trajectory_generation Namespace Reference
Functions
def getMinJerkTraj_QP (dt, tf, x0, xf, constraint=None)
def use_modeling_tool (A, B, N, Q, R, P, x0, xf, constraint=None, umax=None, umin=None, xmin=None, xmax=None)
def getMinJerkTraj (dt, tf, x0, xf)
def getInitState (n)
def getFinalState (n)
def standardize (x)
def sample_func (args)
def main ()
Variables
FILE_DIR = os.path.dirname(os.path.abspath(__file__))
Function Documentation
getFinalState()
def dummy_trajectory_generation.getFinalState (n)
Definition at line 172 of file dummy_trajectory_generation.py.
Referenced by sample_func().
getInitState()
def dummy_trajectory_generation.getInitState (n)
Definition at line 151 of file dummy_trajectory_generation.py.
Referenced by sample_func().
getMinJerkTraj()
def dummy_trajectory_generation.getMinJerkTraj (dt, tf, x0, xf)
Definition at line 116 of file dummy_trajectory_generation.py.
Referenced by sample_func().
getMinJerkTraj_QP()
def dummy_trajectory_generation.getMinJerkTraj_QP (dt, tf, x0, xf, constraint = None)
Definition at line 12 of file dummy_trajectory_generation.py.
References use_modeling_tool().
Referenced by sample_func().
main()
def dummy_trajectory_generation.main ()
Definition at line 236 of file dummy_trajectory_generation.py.
sample_func()
def dummy_trajectory_generation.sample_func (args)
Definition at line 197 of file dummy_trajectory_generation.py.
References getFinalState(), getInitState(), getMinJerkTraj(), and getMinJerkTraj_QP().
standardize()
def dummy_trajectory_generation.standardize (x)
Definition at line 193 of file dummy_trajectory_generation.py.
use_modeling_tool()
def dummy_trajectory_generation.use_modeling_tool (A, B, N, Q, R, P, x0, xf, constraint = None, umax = None, umin = None, xmin = None, xmax = None)
solve MPC with modeling tool for test
Definition at line 51 of file dummy_trajectory_generation.py.
Referenced by getMinJerkTraj_QP().
Variable Documentation
FILE_DIR
dummy_trajectory_generation.FILE_DIR = os.path.dirname(os.path.abspath(__file__))
Definition at line 9 of file dummy_trajectory_generation.py.