OpenHRC: std_utility Namespace Reference
std_utility Namespace Reference
Functions
std::vector< std::vector< long long > > comb (long long n, long long r)
template<typename T >
int min_index (std::vector< T > vec)
template<typename T >
int max_index (std::vector< T > vec)
template<typename T , typename U >
U weightedSum (std::vector< T > weight, std::vector< U > vec)
template<typename _Tp >
_GLIBCXX14_CONSTEXPR _Tp max_abs (std::initializer_list< _Tp > __l)
bool exist_in (const std::vector< std::string > &c, const std::string &v, int &index)
bool exist_in (const std::vector< std::string > &c, const std::string &v)
std::string getDatetimeStr ()
Eigen::VectorXd concatenateVectors (std::vector< Eigen::VectorXd > vecs)
Eigen::VectorXd concatenateVectors (std::vector< KDL::JntArray > vecs)
Eigen::VectorXd concatenateVectors (KDL::JntArray vec)
template<typename T >
std::vector< T > makeVector (T in)
Function Documentation
comb()
std::vector<std::vector<long long> > std_utility::comb (long long n, long long r) inline
Definition at line 12 of file std_utility.h.
Referenced by MyIK::MyIK::addCollisionAvoidance(), and MyIK::MyIK::MyIK().
concatenateVectors() [1/3]
Eigen::VectorXd std_utility::concatenateVectors (KDL::JntArray vec) inline
Definition at line 110 of file std_utility.h.
concatenateVectors() [2/3]
Eigen::VectorXd std_utility::concatenateVectors (std::vector< Eigen::VectorXd > vecs) inline
Definition at line 89 of file std_utility.h.
Referenced by MyIK::MyIK::CartToJntVel_qp(), and concatenateVectors().
concatenateVectors() [3/3]
Eigen::VectorXd std_utility::concatenateVectors (std::vector< KDL::JntArray > vecs) inline
Definition at line 102 of file std_utility.h.
References concatenateVectors().
exist_in() [1/2]
bool std_utility::exist_in (const std::vector< std::string > & c, const std::string & v) inline
Definition at line 70 of file std_utility.h.
References exist_in().
exist_in() [2/2]
bool std_utility::exist_in (const std::vector< std::string > & c, const std::string & v, int & index) inline
Definition at line 58 of file std_utility.h.
Referenced by JointTrajectoryController::cbJointTrajectory(), and exist_in().
getDatetimeStr()
std::string std_utility::getDatetimeStr () inline
Definition at line 75 of file std_utility.h.
References promp_trajectory_demo::time.
Referenced by MultiCartController::getInitParam().
makeVector()
template<typename T > std::vector<T> std_utility::makeVector (T in) inline
Definition at line 115 of file std_utility.h.
Referenced by MyIK::MyIK::CartToJnt(), and MyIK::MyIK::CartToJntVel_qp().
max_abs()
template<typename _Tp > _GLIBCXX14_CONSTEXPR _Tp std_utility::max_abs (std::initializer_list< _Tp > __l) inline
Definition at line 54 of file std_utility.h.
max_index()
template<typename T > int std_utility::max_index (std::vector< T > vec)
Definition at line 36 of file std_utility.h.
min_index()
template<typename T > int std_utility::min_index (std::vector< T > vec)
Definition at line 28 of file std_utility.h.
weightedSum()
template<typename T , typename U > U std_utility::weightedSum (std::vector< T > weight, std::vector< U > vec) inline
Definition at line 43 of file std_utility.h.
References geometry_msgs_utility::sum().
Referenced by MyIK::MyIK::CartToJntVel_qp(), and MyIK::MyIK::CartToJntVel_qp_manipOpt().