OpenHRC: promp_trajectory_service Namespace Reference
promp_trajectory_service Namespace Reference
Functions
def load_data ()
def select_dataset (trajs, mode=3)
def main (mode=1)
Variables
args = sys.argv
Function Documentation
load_data()
def promp_trajectory_service.load_data ()
Definition at line 16 of file promp_trajectory_service.py.
References geometry_msgs_utility.sum().
Referenced by main().
main()
def promp_trajectory_service.main (mode = 1)
Definition at line 44 of file promp_trajectory_service.py.
References load_data(), and select_dataset().
select_dataset()
def promp_trajectory_service.select_dataset (trajs, mode = 3)
Definition at line 27 of file promp_trajectory_service.py.
Referenced by main().
Variable Documentation
args
promp_trajectory_service.args = sys.argv
Definition at line 153 of file promp_trajectory_service.py.