OpenHRC: tf2 Namespace Reference
tf2 Namespace Reference
Functions
Eigen::VectorXd fromMsg (const geometry_msgs::Twist twist, Eigen::VectorXd &vector)
Eigen::VectorXd fromMsg (geometry_msgs::Wrench raw_wrench, Eigen::VectorXd &vector)
Eigen::VectorXd fromMsg (geometry_msgs::Wrench raw_wrench)
geometry_msgs::Wrench toMsg (Eigen::VectorXd vector, geometry_msgs::Wrench &wrench)
void fromMsg (const geometry_msgs::Twist &msg, KDL::Twist &out)
void fromMsg (const geometry_msgs::PoseArray &msg, std::vector< Affine3d > &Ts)
Function Documentation
fromMsg() [1/5]
void tf2::fromMsg (const geometry_msgs::PoseArray & msg, std::vector< Affine3d > & Ts) inline
Definition at line 82 of file transform_utility.h.
References fromMsg().
fromMsg() [2/5]
void tf2::fromMsg (const geometry_msgs::Twist & msg, KDL::Twist & out) inline
Definition at line 73 of file transform_utility.h.
fromMsg() [3/5]
Eigen::VectorXd tf2::fromMsg (const geometry_msgs::Twist twist, Eigen::VectorXd & vector) inline
Definition at line 14 of file Twist.h.
Referenced by CartController::cbArmMarker(), ArmPerception::cbBodyMarker(), ImpedanceController::cbTargetPoses(), CartTrajectoryImpedanceController::cbTargetPoses(), geometry_msgs_utility::cropMinMax(), OmegaInterface::feedback(), XrBodyInterface::feedback(), fromMsg(), StateTopicInterface::getTargetState(), CartTrajectoryImpedanceController::getTrajectories(), main(), OmegaInterface::modifyTargetState(), TwistTopicInterface::setPoseFromTwistMsg(), geometry_msgs_utility::transformFT(), nav_msgs_utility::Odometry::transFromOdom(), nav_msgs_utility::Odometry::transToOdom(), ImpedanceController::updataTaskState(), CartTrajectoryImpedanceController::updateImpedanceTarget(), CartTrajectoryController::updateTargetPose(), ImpedanceController::updateTargetPose(), JointTrajectoryController::updateTargetPose(), and MarkerInterface::updateTargetPose().
fromMsg() [4/5]
Eigen::VectorXd tf2::fromMsg (geometry_msgs::Wrench raw_wrench) inline
Definition at line 25 of file Wrench.h.
References fromMsg().
fromMsg() [5/5]
Eigen::VectorXd tf2::fromMsg (geometry_msgs::Wrench raw_wrench, Eigen::VectorXd & vector) inline
Definition at line 14 of file Wrench.h.
toMsg()
geometry_msgs::Wrench tf2::toMsg (Eigen::VectorXd vector, geometry_msgs::Wrench & wrench) inline
Definition at line 30 of file Wrench.h.
Referenced by ArmPerception::cbBodyMarker(), JointTrajectoryController::cbJointTrajectory(), MarkerInterface::configMarker(), geometry_msgs_utility::cropMinMax(), OmegaInterface::feedback(), nav_msgs_utility::Odometry::fromVector_3dof(), nav_msgs_utility::Odometry::fromVector_6dof(), MyIK::MyIK::getManipulabilityMarker(), rotation_util::getQuaternionErrorYaw(), CartTrajectoryImpedanceController::getTrajectories(), main(), CartController::publishState(), TwistTopicInterface::setPoseFromTwistMsg(), and geometry_msgs_utility::transformFT().