
root_frame: "base_link" # IK calculation base frame (for multi-follower)

controller: "Velocity" # "Position" or "Velocity"


solver: "MyIK"

self_collision_avoidance: false

control_freq: 30.0



follower_list: # robot namespace list. They should be unique. ("") means the robot has no namespace
  crane_x7:
    - ""

priority: "Manual" #"Automation" #  (for multi-follower)
MF_mode: "Individual" #"Parallel" #   (for multi-follower)

# Type of solving IK. "Concatenated" mode solve IK for all robots at once. "Order" mode solve IK for each robot in order. "Parallel" mode solve IK for all robots in multi thread.
# When you operate single robot, "Concatenated" mode is equivalent to "Order" mode.
IK_mode: "Concatenated" # "Order" # "Parallel" #
