
root_frame: "base_link" # IK calculation base frame (for multi-follower)

controller: "Velocity" # "Position" or "Velocity"


solver: "MyIK"

self_collision_avoidance: true

control_freq: 30.0



follower_list: # robot namespace list. They should be unique. ("") means the robot has no namespace
  crane_x7:
    - ""

priority: "Manual" #"Automation" #  (for multi-follower)
MF_mode: "Individual" #"Parallel" #   (for multi-follower)
IK_mode: "Order" # (for multi-follower)
