chain_start: "base_link" # base frame of commands
chain_end: "gripper_link" # target eff frame
root_frame: "base_link" # IK calculation base frame (for multi-follower)

# controller: "Velocity"
# controller_topic_name: "joint_group_vel_controller"

controller: "TrajectoryAction"
controller_topic_name: "arm_with_torso_controller"

solver: "MyIK"

control_freq: 30.0

initIKAngle: [0, 0., 0, 0, 0, 0, 0, 0] # size of this should be equal to DoF
initial_pose: [0.2, 0.3, 1.1, 0, 0, 0]

follower_list: # robot namespace list. They should be unique. ("") means the robot has no namespace
  - ""
  # - "toroboarm_2"
  # - "toroboarm_3"
  # - "toroboarm_4"
  # - "toroboarm_5"
  # - "toroboarm_6"
  # - "toroboarm_7"
  # - "toroboarm_8"
  # - "toroboarm_9"

priority: "Manual" #"Automation" #  (for multi-follower)
MF_mode: "Individual" #"Parallel" #   (for multi-follower)
IK_mode: "Order" # (for multi-follower)
