chain_start: "base_link" # base frame of commands
chain_end: "tool0" # target eff frame
root_frame: "world" # IK calculation base frame (for multi-follower)

controller: "Velocity" # "Position" or "Velocity"
publisher: "Velocity" # "Position" or "Velocity" or "Trajectory" or "TrajectoryAction"
topic_namespace: "joint_group_vel_controller"

solver: "MyIK"

self_collision_avoidance: true

control_freq: 500.0

initIKAngle: [0, -1., 2., -2.5, -1.5, 0] # size of this should be equal to DoF

# initial_pose_frame: test # default frame is same as chain_start
initial_pose: [0.35, 0.0, 0.3, 3.141592, 0, 0] # [x, y, z, roll, pitch, yaw]

follower_list: # robot namespace list. They should be unique. ("") means the robot has no namespace
  - ""
  # - "toroboarm_2"
  # - "toroboarm_3"
  # - "toroboarm_4"
  # - "toroboarm_5"
  # - "toroboarm_6"
  # - "toroboarm_7"
  # - "toroboarm_8"
  # - "toroboarm_9"

priority: "Manual" #"Automation" #  (for multi-follower)
MF_mode: "Individual" #"Parallel" #   (for multi-follower)
IK_mode: "Order" # (for multi-follower)
