seed:
  chain_start: "body_link" # base frame of commands
  chain_end: "l_hand_link" # target eff frame

  publisher: "Trajectory" # "Position" or "Velocity" or "Trajectory" or "TrajectoryAction"
  topic_namespace: "larm_controller"


  initIKAngle: [0, 0., 0, 0, 0, 0, 0, 0] # size of this should be equal to DoF
  initial_pose: [0.45, 0.25, 0.12, 0, -1.57079, 0] # [x, y, z, roll, pitch, yaw]