root_frame: "world" # IK calculation base frame (for multi-follower)

controller: "Velocity" # "Position" or "Velocity"


solver: "MyIK"

self_collision_avoidance: false

control_freq: 500.0


follower_list: # robot namespace list. They should be unique. ("") means the robot has no namespace
  panda: # robot config name
    - "" # robot namespace


priority: "Manual" #"Automation" #  (for multi-follower)
MF_mode: "Individual" #"Parallel" #   (for multi-follower)
IK_mode: "Order" # "Concatenated" #(for multi-follower)
