name: ROS build workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CATKIN_WS: /home/runner/work/catkin_ws
    steps:
    - uses: actions/checkout@v3

    - name: Setup ROS
      uses: ros-tooling/setup-ros@v0.6
      with:
        required-ros-distributions: noetic

    - name: Install X11 LibXCB for OpenXR
      run: sudo apt install libx11-xcb-dev libxcb-dri2-0-dev libxcb-glx0-dev libxcb-icccm4-dev libxcb-keysyms1-dev libxcb-randr0-dev

    - name: Init workspace
      run: |
        source /opt/ros/noetic/setup.bash
        mkdir -p ${CATKIN_WS}/src
        ln -s ${GITHUB_WORKSPACE} ${CATKIN_WS}/src/

    - name: pre build
      run: |
        source /opt/ros/noetic/setup.bash
        cd ${CATKIN_WS}/src/OpenHRC
        git submodule update --init --recursive
        rosdep update
        rosdep install --ignore-src -y -r --from-paths ./ 

    - name: build
      run: |
        source /opt/ros/noetic/setup.bash
        cd ${CATKIN_WS}
        rospack profile
        catkin build -DCMAKE_BUILD_TYPE=Release

    - name: test
      run: |
        source /opt/ros/noetic/setup.bash
        cd ${CATKIN_WS}
        catkin test
        
